### ISSUE TITLE
Simple image filters

### ISSUE THREAD

**Issue by fsimchen** [libvips/php-vips#100]
How can I aply some simple filters like:

```php
$imagick->whiteThresholdImage($color);
$imagick->blackThresholdImage($color);
$imagick->thresholdimage($threshold * \Imagick::getQuantum(), $channel);

$kernel = \ImagickKernel::fromBuiltIn(\Imagick::KERNEL_SQUARE,"1");
$imagick->morphology(\Imagick::MORPHOLOGY_CLOSE, 1, $kernel);

$imagick->blurImage(5, 1);
$imagick->despeckleImage();
$imagick->normalizeImage();
$imagick->enhanceImage();
$imagick->autoLevelImage();
```

**Comment by jcupitt** [comment]
Hello @fsimchen,

Did you find the docs? They have lots of examples:

https://libvips.github.io/php-vips/docs/classes/Jcupitt.Vips.Image.html

Use the relational operators for thresholding, eg.

```php
$mask = $image->more(128);
```

Makes a true/false image. These are uint8 images with 0 for false and 255 for true. You can combine them with `->and()` and `->or()`. You can use eg.:

```php
$mask = $image->more([128, 0, 23]);
```

To test each band of an RGB separately. You can compare images too, eg.:

```php
$mask = $image->more([128, 0, 23])->and($image->more($image2));
```

Use `newFromArray` to make a structuring element, and eg. `->dilate()` to apply it. Structuring elements have 0 for unset, 255 for set and 128 for don't care.

https://libvips.github.io/libvips/API/current/libvips-morphology.html#vips-morph

Have a look at `->gaussblur()`. There are a range of histogram operators, see `->hist_equal()` etc.

**Comment by jcupitt** [comment]
nip2 is very handy for development. Save an intermediate image to a vips file and view it with eg.:

```php
$image->writeToFile("x.v");
system("nip2 x.v");
system("rm x.v");
```

Now you can pause execution and examine intermediates.

https://github.com/libvips/nip2

**Comment by fsimchen** [comment]
$mask = $image->more(128);

Did the trick, thanks!
