### ISSUE TITLE
Set icc profile on image

### ISSUE THREAD

**Issue by vnkapoor** [libvips/php-vips#106]
I want to add sRGB icc profile on my image if interpretation is CMYK. I tried below code but didn't got any solution. I saw icc_transform, icc_import and icc_export method but not exactly get the idea which is for add icc the profile.

```
$iccProfilePath = 'sRGB2014.icc';
$image = Vips\Image::newFromFile($arg[1], ["access" => "sequential"]);
if ($image->interpretation == "cmyk") {
    $image = $image->icc_import(["embedded" => true, "input_profile" => $iccProfilePath]);
}
$image->writeToFile($arg[2]);
```

**Comment by jcupitt** [comment]
Hello @vnkapoor,

You need to give a lot more information: input images, the command you ran, expected output, any error messages, actual output.

**Comment by vnkapoor** [comment]
@jcupitt I am not getting error, here i add my input and output image, hope it will be helpful to you.
Input Image - 
![inputimg](https://user-images.githubusercontent.com/22096149/92910310-9486bb80-f445-11ea-8900-47d22ca8ffaf.jpg)

Output image -
![outputimg](https://user-images.githubusercontent.com/22096149/92910371-9fd9e700-f445-11ea-8446-a05331ead177.png)

Command i am using for get image icc-data
`vipsheader -a abc.jpg`

**Comment by jcupitt** [comment]
Ah, you want to transform CMYK images to sRGB, is that right? Use:

```
vips icc_transform park.jpg x.jpg srgb
```

At the command-line to make:

![x](https://user-images.githubusercontent.com/580843/92911332-b457b880-f420-11ea-9757-bc08f556d0cc.jpg)

In PHP it would be:

```php
$image = Vips\Image::newFromFile("park.jpg", ["access" => "sequential"]);
$image = $image->icc_transform("srgb");
$image->writeToFile("x.jpg");
```

`icc_transform` moves an image between two device spaces, so in this case from CMYK to sRGB. Your input image has a profile, so you don't need to supply a CMYK input profile. libvips has a built-in srgb profile it'll pick automatically if you ask for srgb output.

**Comment by vnkapoor** [comment]
@jcupitt I tried your above code it works. But i applied SRGB icc profile using imagick and vips but both image have some difference, here i added both images. For imagick i am using sRGB2014.icc profile.

Add icc profile using Imagick
![imagick_icc](https://user-images.githubusercontent.com/22096149/92913705-a158de80-f448-11ea-9736-54b109684962.png)

Add icc profile using VIPS
![vips_icc](https://user-images.githubusercontent.com/22096149/92913750-a87fec80-f448-11ea-8221-a2a4c87a1305.png)

**Comment by jcupitt** [comment]
I would try setting the rendering intent to perceptual, or using your own srgb profile.

**Comment by vnkapoor** [comment]
@jcupitt How can i add my icc profile instead of vips SRGB. Is that any method for that.
For ex - If i want to add `CoatedFOGRA27.icc` on my image, how can i achieve that?

**Comment by jcupitt** [comment]
But that's a CMYK profile. You can't swap an RGB profile for a CMYK one.

Like I said, try perceptual rendering intent:

```
vips icc_transform park.jpg x.jpg srgb --intent perceptual
```

To make:

![x3](https://user-images.githubusercontent.com/580843/93018460-d0498e80-f5c7-11ea-8236-327655cbe231.jpg)

(default on the left, perceptual on the right)
