### ISSUE TITLE
Add svg path on image

### ISSUE THREAD

**Issue by user143-git** [libvips/php-vips#109]
I am using vips PHP library. I want to add svg path on my image. I implemented below code for that but it's not giving me expected output. The problem is how can I set svg path according to the actual image height & width. I tried using resize and thumbnail but it doesn't give me expected output. Also I want to fill the grey color on my actual image blocks like in expected output image.

```
$background = Vips\Image::newFromFile($arg[1], ['access' => 'sequential']);
$svg = Vips\Image::svgload_buffer('<svg  viewBox="0 0 700 700>
  <path 
    d="M0 200 v-200 h200 
    a100,100 90 0,1 0,200
    a100,100 90 0,1 -200,0
    z" stroke="#fff" fill="transparent"/>
</svg>');
// $svg = $svg->resize(2.5);
$svg = $svg->thumbnail_image(700, ['height' => 700, 'size' => 'both']);
$image = $background->colourspace('b-w');
$image = $background->composite($svg, 'dest-in');
$image->writeToFile([$arg2], ['background' => [128, 128, 128], 'Q' => 100]);
```
I added colourspace 'b-w' on background image but it gives me same result which i mentioned in above output. Also when i applied viewBox="0 0 700 700", there is no change in svg. I want to adjust svg height and width according to image height & width

Below is the image on which I added my svg path
![actualimage](https://user-images.githubusercontent.com/71428831/93432546-51b06200-f8e3-11ea-805a-ed8e5b92477b.jpg)

My vips output image
![vipsoutput](https://user-images.githubusercontent.com/71428831/93432572-5bd26080-f8e3-11ea-93cc-bcdf802627f1.jpg)

Expected output image
![expectedop](https://user-images.githubusercontent.com/71428831/93432593-642a9b80-f8e3-11ea-84a4-4ff67a85fc1a.jpg)

**Comment by jcupitt** [comment]
Hello @user143-git,

It looks like you want to turn your background image to monochrome, so add `colourspace('b-w')`.

Rather than rendering the SVG and then resizing it, it's better to make it the correct size to start with. You can set the `width` and `height` properties to do this.

Try:

```php
#!/usr/bin/php
<?php

require __DIR__ . '/vendor/autoload.php';
use Jcupitt\Vips;

$background = Vips\Image::newFromFile($argv[1], ['access' => 'sequential']);
$width = $background->width;
$height = $background->height;
$svg = Vips\Image::svgload_buffer(<<<EOF
<svg
  viewBox="0 0 300 300" 
  width="$width"
  height="$height">
  <path 
    d="M0 200 v-200 h200 
    a100,100 90 0,1 0,200
    a100,100 90 0,1 -200,0
    z" stroke="#fff" fill="white"/>
</svg>
EOF);
$image = $background->colourspace('b-w')->composite($svg, 'dest-in');
$image->writeToFile($argv[2], ['background' => [128, 128, 128], 'Q' => 100]);
```

I can run like this:

```
$ ./try318.php ~/pics/bg.jpg x.jpg
```

To generate:

![x](https://user-images.githubusercontent.com/580843/93434462-19e3f300-f8c0-11ea-9b4e-01815cca5ced.jpg)

**Comment by user143-git** [comment]
@jcupitt I tried your above code it works, but as you can see in below image the svg left some space at the top of the image. Also the `viewBox="0 0 300 300"` this value is works for all the images or i have to change it for different images?

![image](https://user-images.githubusercontent.com/71428831/93439140-ce473e80-f8eb-11ea-9845-fa8b8fe106ee.png)

**Comment by jcupitt** [comment]
The "300 300" is related to the coordinates in your path. "width" and "height" set the size in pixels that the path renders at.

You should probably read an SVG tutorial, eg. https://www.w3schools.com/graphics/svg_intro.asp

**Comment by vnkapoor** [comment]
@jcupitt in the expected output image  and vips output image, color of the actual image(which is inside the svg) is different in vips output image. Is it possible to do same like my expected output image?

**Comment by user143-git** [comment]
@jcupitt in the expected output image and vips output image, color of the actual image(which is inside the svg) is different in vips output image. Is it possible to do same like my expected output image?

**Comment by jcupitt** [comment]
I don't know why your green image became monochrome under imagemagick. I guessed it was just converted to monochrome, but perhaps something else happened? You'll need to investigate.
