### ISSUE TITLE
How to add icc profile to image?

### ISSUE THREAD

**Issue by jhony1104** [libvips/php-vips#110]
I am trying to convert a cmyk jpeg without attached ICC profile to an image in the srgb colorspace, which results in the error `vips_colourspace: no known route from 'cmyk' to 'srgb'`.

This is - as I understand it - fixed in the current version of libvips, by using a [fallback icc profile](https://github.com/libvips/libvips/blob/master/libvips/colour/profiles/cmyk.icm).

Since I don't have the current version available on my system, I need to add this icc profile manually.

How can I do this?

```php
if ($image->interpretation == "cmyk") {
    // what can i do here (or anywhere else) to add the fallback icc profile?
}
```

This issue is possible related to #106.

**Comment by jcupitt** [comment]
Hi @jhony1104,

Use `icc_transform`, eg:

```php
$image = $image->icc_transform("my/srgb/profile.icm", [
    "intent" => "perceptual",
    "input-profile" => "my/cmyk/profile.icm"
]);
```

https://libvips.github.io/libvips/API/current/libvips-colour.html#vips-icc-transform

**Comment by jhony1104** [comment]
Thank you for your quick and helpful response
