### ISSUE TITLE
"heic" is not a known file format

### ISSUE THREAD

**Issue by edent** [libvips/php-vips#111]
When I try to open a HEIC file, I get the error message 

> PHP Fatal error:  Uncaught Jcupitt\Vips\Exception: VipsForeignLoad: "test1.heic" is not a known file format

Is this likely to be a problem with my installation, or something else?

**Comment by jcupitt** [comment]
Hello @edent,

Your libvips has probably not been built with HEIC support. You need libheif and libde265.

**Comment by mstaack** [comment]
i have the same issue.

is there any complete setup guide for getting php / vips / heic all working on ubuntu 20 ?

guess i am somehow missing the heif in my vips build?

vips-8.9.1-Sun Feb 23 08:51:26 UTC 2020

```$ pkg-config libheif --print-variables
builtin_h265_decoder
builtin_h265_encoder
exec_prefix
includedir
libdir
pcfiledir
prefix
```

```
$ vips heifload
vips: unknown action "heifload
```

**Comment by mstaack** [comment]
so i got this working with basically this:

````
apt install php-pear libheif-dev
wget https://github.com/libvips/libvips/releases/download/v8.10.5/vips-8.10.5.tar.gz
tar xf vips-8.10.5.tar.gz
cd vips-8.10.5
./configure
make
sudo make install
sudo ldconfig
pecl install vips
# enable with mod-available in php config
```

**Comment by jcupitt** [comment]
I made a demo dockerfile for php-vips with HEIC on ubuntu 20.04:

https://github.com/jcupitt/docker-builds/tree/master/php-vips-ubuntu-20.04

It does more or less what you do.

**Comment by mstaack** [comment]
@jcupitt thanks, did a little update.
