### ISSUE TITLE
AVIF with AV1 compression for Web

### ISSUE THREAD

**Issue by andrefelipe** [libvips/php-vips#112]
Hello John, 

I am trying to create AVIF images for web (supported in Chrome) and get into this error:

```php
$data = $image->writeToBuffer(
    '.avif',
    [
        'compression' => 'av1',
    ]
);

Jcupitt\Vips\Exception: heifsave: Unsupported compression
```

I looked everywhere I could, went to source code and tried to nail it down, but I need your help. Also tried to reinstall vips, vip-php-ext but same error.

I guess it's related on the AV1 support I have on my libheif library, but it's all the latest.
```
macOS
vips 8.10.2_4
libheif 1.9.1
php-vips v1.0.8
php-vips-ext 1.0.12
```

Do you have an idea?

For context, if I remove the `compression` option it does save the file just fine, and Mac can open the file in preview. But Chrome does not load such image. I guess by removing the compression the file is encoded in HEIF.

Thanks!

**Comment by jcupitt** [comment]
Hello @andrefelipe,

The `Unsupported compression` message comes from libheif. You'll need to build it with avif support.

**Comment by andrefelipe** [comment]
Thanks John!

Tried to install libheif from source but no success yet. Guess I'll wait till an easier way to install.

Best regards
