### ISSUE TITLE
[question] How to write IPTC?

### ISSUE THREAD

**Issue by andrefelipe** [libvips/php-vips#113]
Is there a way to write IPTC data in LibVips?

My goal is to write copyright data into the images.

Already research how to do it, but looks like it's out of the scope of an image library, but anyway, thought about asking.

Thanks!

**Comment by andrefelipe** [comment]
Well, I see that we can set IPTC with:
```php
$image->set('iptc-data', 'binary data here');
```
But data is binary, looked complex to create.

**Comment by jcupitt** [comment]
Hi @andrefelipe,

That's right, you can read and write the data with libvips, but creating it is up to you.

I would look instead at XMP -- it's the same as IPTC, more or less, but you represent the data as XML, so it's much simpler to create and parse.

**Comment by andrefelipe** [comment]
I understood now. Thank you for your time!
