### ISSUE TITLE
thumbnail not accepting "n" option for gif

### ISSUE THREAD

**Issue by Sud4** [libvips/php-vips#115]
```
$image = Vips\Image::thumbnail('./org1.gif', 200, ['n' => -1]);
$image->writeToFile("1.gif");
```
Fatal error: Uncaught Jcupitt\Vips\Exception: thumbnail: no property named `n' in /vendor/jcupitt/vips/src/Image.php:778

**Comment by jcupitt** [comment]
Hello @Sud4,

Try:

```php
$image = Vips\Image::thumbnail('./org1.gif[n=-1]', 200);
```

**Comment by Sud4** [comment]
Thanks you for the quick response,
above code works for local file. my user case is below

```
$image = Vips\Image::thumbnail_buffer(file_get_contents('https://libvips.github.io/libvips/assets/images/manybanana.gif'), 200);
echo $image->writeToBuffer('.gif');
```
How can i pass "n" option when pulling image from url, and when i try to use writeToBuffer it gives error.

Fatal error: Uncaught Jcupitt\Vips\Exception: magicksave_buffer: libMagick error: no decode delegate for this image format `' @ error/blob.c/ImagesToBlob/1993 in

**Comment by jcupitt** [comment]
`thumbnail_buffer` lets you pass an extra option string:

```php
$image = Vips\Image::thumbnail_buffer(buffer, 200, ['option-string' => 'n=-1']); 
```

Unfortunately, php-doc does not let us document the contents of the option hash:

https://libvips.github.io/php-vips/docs/classes/Jcupitt-Vips-ImageAutodoc.html#method_thumbnail_buffer

But you can check the main libvips docs:

https://libvips.github.io/libvips/API/current/libvips-resample.html#vips-thumbnail-buffer

**Comment by Sud4** [comment]
Thank You, it works.
