### ISSUE TITLE
GIF image embed extend not animating. 

### ISSUE THREAD

**Issue by Sud4** [libvips/php-vips#116]
Hi 

When i try to extend the gif image the animation is not working, below is the code.

```php
$image = Vips\Image::thumbnail_buffer($bufferData, $newWidth, ['option-string' => 'n=-1', "height" => $newHeight]);
$x = ($newWidth - $image->width) / 2;
$y = ($newHeight - $image->height) / 2;
$image = $image->embed($x, $y, $newWidth, $newHeight, [
    'extend' => Extend::WHITE,
]);
```

**Comment by jcupitt** [comment]
Hi again, if you change the size of each frame, you need to update `page-height`.

Post a complete program plus some sample data.

**Comment by Sud4** [comment]
Below is the complete code for GIF resizing, when i do extent animation not working. 

```php
$bufferData = file_get_contents('https://user-images.githubusercontent.com/580843/88278742-cea3ce80-ccda-11ea-8a32-593d853418c5.gif');
$image = Vips\Image::thumbnail_buffer($bufferData, 200, ['option-string' => 'n=-1', "height" => 300]);
$x = (200 - $image->width) / 2;
$y = (300 - $image->height) / 2;
$image = $image->embed($x, $y, 200, 300, [
    'extend' => Extend::WHITE,
]);
$buffer = $image->writeToBuffer('.gif', [
    'optimize-gif-frames' => 1,
    'optimize-gif-transparency' => 1,
    'format' => 'gif',
]);
header("Content-Type: image/gif");
echo $buffer;
```
Output
![image](https://user-images.githubusercontent.com/2331341/110421638-e9894e80-80c3-11eb-932a-5f60e6486293.png)

**Comment by jcupitt** [comment]
Ah I see.

Sorry, it's more complicated. libvips represents animated images as very tall, thin strips. There are some notes here:

https://libvips.github.io/libvips/2017/03/16/What's-new-in-8.5.html#toilet-roll-images

So you need to load the animation, chop it into separate pages, make each page larger with embed, reassemble into a tall thin strip again, set the new page size, and write.

```
#!/usr/bin/php 
<?php

require __DIR__ . '/vendor/autoload.php';
use Jcupitt\Vips;

$target_width = 200;
$target_height = 300;
    
$bufferData = file_get_contents($argv[1]);
$image = Vips\Image::thumbnail_buffer($bufferData, $target_width, [
  'option-string' => 'n=-1', 
  'height' => $target_height
]);
  
// the size of each frame
$page_height = $image->get('page-height');
$n_pages = $image->Ysize / $page_height;

// cut into pages
$pages = [];
for ($page = 0; $page < $n_pages; $page++ )
  $pages[] = $image->crop(0, $page * $page_height, $image->width, $page_height);

// centre each frame in the target size
$x = ($target_width - $image->width) / 2;
$y = ($target_height - $page_height) / 2;
for ($page = 0; $page < $n_pages; $page++ ) 
  $pages[$page] = $pages[$page]->embed($x, $y, $target_width, $target_height, [
    'extend' => Vips\Extend::WHITE,
  ]);

// reassemble the pages into a tall, thin image, and set the page height
$image = Vips\Image::arrayjoin($pages, ['across' => 1]);
$image->set("page-height", $target_height);
  
$buffer = $image->writeToBuffer('.gif', [
  'optimize-gif-frames' => TRUE, 
  'optimize-gif-transparency' => TRUE,
  'format' => 'gif'
]);
header("Content-Type: image/gif");
echo $buffer;
```

If I run:

```
$ ./gif-embed.php https://user-images.githubusercontent.com/580843/88278742-cea3ce80-ccda-11ea-8a32-593d853418c5.gif > x.gif
```

I get this:

![x](https://user-images.githubusercontent.com/580843/110482170-45fa6700-80e0-11eb-9eac-ed71521720cc.gif)

**Comment by Sud4** [comment]
Solution works perfectly fine is there way to speed up the process may be my reducing quality.

**Comment by Sud4** [comment]
when I try to resize the image with gifsicle it's take around 600ms, same GIF when try with PHP code it's takes 15 seconds.
wondering how can there be so much time difference. however it's doesn't support embed functionality but still making a point.

Sample code with different GIF
```bash
wget -qO- https://user-images.githubusercontent.com/580843/88278742-cea3ce80-ccda-11ea-8a32-593d853418c5.gif | gifsicle --resize-fit 870x300
```

**Comment by kleisauke** [comment]
@jcupitt Just wondering, wouldn't it be faster (when `x == 0` and `$image->width == $target_width`) if you rearrange the tall image into a vertical grid (with `vips_grid`), do the embed (i.e., preserving the width, change height only), and then rearrange the vertical grid back into a thin tall image? I noticed this while working on PR https://github.com/lovell/sharp/pull/2789.

**Comment by jcupitt** [comment]
Oh, that's an interesting idea. 

But I've no clue! We'd need to do some experiments.

**Comment by kleisauke** [comment]
It makes a difference of a few ms (after testing it with commit https://github.com/lovell/sharp/pull/2789/commits/45c594e342aa5556c703f0cd70920760a742bbf3?w=1), so it is probably negligible.
