### ISSUE TITLE
Add docs to php.net

### ISSUE THREAD

**Issue by J0WI** [libvips/php-vips#120]
Would be great to have the documentation on a common place like here: https://www.php.net/manual/en/refs.utilspec.image.php

I think the source of this is here: https://github.com/php/doc-en/tree/master/reference

**Comment by jcupitt** [comment]
Hi @J0WI,

Sure, that'd be great. It looks like they need docbook, so we'd just need a way to generate that from our existing phpdoc files.

Do you know if that process is documented anywhere?

**Comment by J0WI** [comment]
> Do you know if that process is documented anywhere?

I haven't found any details
