### ISSUE TITLE
Unable to resize svg image

### ISSUE THREAD

**Issue by sudhir02** [libvips/php-vips#121]
Hi @jcupitt

i am tyring to resize the svg images and gettin this error, is there anything i am missing.

`Uncaught Jcupitt\Vips\Exception: VipsForeignSave: "test.svg" is not a known buffer format`

```php
<?php

require __DIR__ . '/vendor/autoload.php';

use Jcupitt\Vips;
use Jcupitt\Vips\Extend;

$newWidth = 200;
$newHeight = 50;


$bufferData = file_get_contents('./ESCH_Beauty_White_Logo Copy.svg');
$image = Vips\Image::thumbnail_buffer($bufferData, $newWidth, ['height' => $newHeight]);

$x = ($newWidth - $image->width) / 2;
$y = ($newHeight - $image->height) / 2;

if ($image->hasAlpha()) {
    $image = $image->embed($x, $y, $newWidth, $newHeight, [
        'extend' => Extend::BACKGROUND,
        'background' => 0
    ]);
} else {
    $image = $image->embed($x, $y, $newWidth, $newHeight, [
        'extend' => Extend::BACKGROUND,
        'background' => 255
    ]);
}
echo $image->writeToBuffer('test.svg');
```
php configuration 

![image](https://user-images.githubusercontent.com/2331341/128314805-438a6ef4-f2bd-41ae-8b07-4342f5c55adc.png)

**Comment by jcupitt** [comment]
Hi @sud4, could you share the SVG image it's failing to recognize?

**Comment by sud4** [comment]
Sure, 
https://www.dropbox.com/s/ddsuvr5vubxnyvb/ESCH_Beauty_White_Logo%20Copy.svg?dl=0
This is a transparent image can be seen on black background.

**Comment by jcupitt** [comment]
A small variation on your program works fine here, I'm not sure what's wrong.

```php
#!/usr/bin/php
<?php

require __DIR__ . '/vendor/autoload.php';

use Jcupitt\Vips;

$newWidth = 200; 
$newHeight = 50;

$bufferData = file_get_contents($argv[1]);
$image = Vips\Image::thumbnail_buffer($bufferData, $newWidth, ['height' => $newHeight]);

$x = ($newWidth - $image->width) / 2;
$y = ($newHeight - $image->height) / 2;

if ($image->hasAlpha()) {
    $image = $image->embed($x, $y, $newWidth, $newHeight, [
        'extend' => 'background',
        'background' => 0
    ]);
} else {
    $image = $image->embed($x, $y, $newWidth, $newHeight, [
        'extend' => 'background',
        'background' => 255
    ]);
}
echo $image->writeToBuffer($argv[2]);
```

Then:

```
$ ./copy-buffer.php ~/pics/ESCH_Beauty_White_Logo.svg .jpg[background=0] > x.jpg
```

To make:

![x](https://user-images.githubusercontent.com/580843/128339295-c6200b89-2444-4a29-9205-2366386312f5.jpg)

You could try testing at the vips command-line. You should see something like:

```
$ vipsheader ESCH_Beauty_White_Logo.svg 
ESCH_Beauty_White_Logo.svg: 140x9 uchar, 4 bands, srgb, svgload
```

**Comment by sud4** [comment]
Hi @jcupitt 

i am getting `Segmentation fault`

```sh
./copy-buffer.php ./ESCH_Beauty_White_Logo.svg .jpg[background=0] > x.jpg
Segmentation fault
```

```sh
vipsheader ESCH_Beauty_White_Logo.svg
ESCH_Beauty_White_Logo.svg: 140x9 uchar, 4 bands, srgb, svgload
```
can i convert svg image to svg?

**Comment by jcupitt** [comment]
Perhaps your librsvg is too old? I see:

```
$ pkg-config librsvg-2.0 --modversion
2.48.9
```

**Comment by sud4** [comment]
i am on centos 7, librsvg version is `2.40.20`

This works fine.
```bash
vips copy ESCH_Beauty_White_Logo.svg x.jpg[background=0]
````
and this gives error
```bash
vips copy ESCH_Beauty_White_Logo.svg x.svg[background=0]
VipsForeignSave: "x.svg" is not a known file format
```

**Comment by jcupitt** [comment]
Oh I'm so sorry, I didn't read your original report carefully enough.

No, libvips will not write SVG. libvips is a raster image processing library and cannot write any vector format. 

It can render raster images from a vector source, but that's it.

**Comment by sud4** [comment]
I got the point, i think i can parse svg file as xml and i can edit height and width to resize it.

Thank you.
