### ISSUE TITLE
How can i generate a image with round radius like this?

### ISSUE THREAD

**Issue by jonny77** [libvips/php-vips#135]
orig image:
![image](https://user-images.githubusercontent.com/1962170/157214562-3db8c425-138e-4d0c-99a7-c8c63166564c.png)

wanted image:
![822481f32d15cde3ef857d720b31d4c9](https://user-images.githubusercontent.com/1962170/157214882-85245ef6-1aa5-4054-a22b-f1d9d97cf7ac.png)

**Comment by jcupitt** [comment]
Hello @jonny77,

The simplest way is to mask with an SVG. See https://github.com/libvips/libvips/discussions/2271
