### ISSUE TITLE
Document a way to install libvips without the dependecy hell

### ISSUE THREAD

**Issue by cypherbits** [libvips/php-vips#141]
Hello,

This is a great project with an awesome performance but I think it is not used by many project just for the dependency hell when you want to install and use it.

When you go to install libvips on a Debian/Ubuntu you get about 1GB of dependencies (even Firefox or Xorg). This is wrong for containers and modern deployments.

Is there at least a documented way to compile, install and configure PHP to use libVIPS? Could you provide a precompiled .so?

Thanks.

**Comment by jcupitt** [comment]
Hi @cypherbits,

Yes, the debian libvips package is extremely heavy by default. It recommends the libvips GUI, and that in turn pulls in a lot of other stuff.

Try:

```
apt-get install --no-install-recommends libvips42
```

It's only 35mb.

**Comment by cypherbits** [comment]
Hi, tried that and downloaded about 15MB with 75MB of disk storage. That is much better than the 1GB from before.
Many thanks! This should be documented right on the readme!

**Comment by jcupitt** [comment]
It's a standard Debian thing, but you're right perhaps not everyone knows. I'll add a note.

Thanks for suggesting this!
