### ISSUE TITLE
I get: Uncaught FFI\Exception: Failed resolving C function 'vips_error_buffer_copy'

### ISSUE THREAD

**Issue by jhernandis** [libvips/php-vips#145]
Hi, I'm newbie at php-vips, sorry if that issue it's very obvious.

I've installed libvips, enabled ffi and added "jcupitt/vips" via composer.

I'm trying the PHP example, and when I run it get that error:
`PHP Fatal error:  Uncaught FFI\Exception: Failed resolving C function 'vips_error_buffer_copy' in ...`

Which step I've missed?

I'm running Debian 10 on WSL2
Using PHP 7.4
Using vips-8.7.4-Sat Nov 21 16:50:57 UTC 2020

Thanks.

**Comment by jhernandis** [comment]
I've reinstalled libvips using: `apt install libvips42 libvips-tools libvips-doc libvips-dev -yy`

And now works fine.

**Comment by Spongert** [comment]
> I've reinstalled libvips using: `apt install libvips42 libvips-tools libvips-doc libvips-dev -yy`
> 
> And now works fine.

Just for the record. I have exactly the same issue. Using Debian 10.12, PHP 7.4. However, reinstalling as you described does not solve it. Neither does running the composer update unfortunately.
