### ISSUE TITLE
Intallation/usage under Windows?

### ISSUE THREAD

**Issue by massimosala** [libvips/php-vips#148]
Hi
Sorry to bother you, but I cannot understand how to install on Windows.

I already get 
[vips](https://github.com/libvips/build-win64-mxe/releases/download/v8.12.2/vips-dev-w64-web-8.12.2.zip
)

Where could I get the _php_libvips.dll_ ?
If the dll is now obsolete, how can I get the plain php bindings?

Notes:
* I tried to use PECL and PEAR, but for each package they abort on "cannot compile".
* I am using php 7.4

**Comment by jcupitt** [comment]
You need php-vips 2.0.3 (latest stable). It does not require a dll for the binding.

**Comment by massimosala** [comment]
Hi John
I got the vips
[library](https://github.com/libvips/build-win64-mxe/releases/download/v8.12.2/vips-dev-w64-web-8.12.2.zip)

Now, on windows, how can I install php-vips 2.0.3 ?
