### ISSUE TITLE
change quality before writing the image for better performance 

### ISSUE THREAD

**Issue by Mohammad-Khazaee** [libvips/php-vips#152]
Hi 
i always modify images and then change the quality whenever i save it 
here is a example: 
```
        $image = Image::thumbnail('../public/image.png',300);
        $image = $image
            ->colourspace(Interpretation::LCH)
            ->linear([$brightness = 0.8 , $saturation = 0.6 , 1.0]);

            $image->writeToFile('image-modified.webp', [
                'Q' => 75
            ]);
```
For better performance, first change the quality
like this:
```
        $image = Image::thumbnail('../public/image.png',300);
        $image = $image->quality(75)   // <--*-----------*---------------*-
        $image = $image
            ->colourspace(Interpretation::LCH)
            ->linear([$brightness = 0.8 , $saturation = 0.6 , 1.0]);

            $image->writeToFile('image-modified.webp');
```
 
is there any method like this that first i can change the quality ?

**Comment by jcupitt** [comment]
Hi @Mohammad-Khazaee,

All libvips images are simply large arrays. There's not really any idea of quality -- a number is just a number.

Some operations have fast, or approximate modes. For example, convolution has a `precision` parameter which you can set to `integer` for a useful speedup.

**Comment by Mohammad-Khazaee** [comment]
thanks a lot for for quick respond
