### ISSUE TITLE
response cropped image without saving image

### ISSUE THREAD

**Issue by Mohammad-Khazaee** [libvips/php-vips#154]
Hi i created a laravel app for image api like this https://imgix.com  
but here is a problem 
i wanna response the file without saving it in my for example:
my current laravel app
```php
$image = Image::newFromFile(storage_path('image.png') ', ['access' => 'sequential']);
$image = $image->crop(0,0,100,100);
$image = $image->writeToFile(storage_path('new-image.png') ,['Q' => 100]);
return response()->file(storage_path('new-image.png'));
```
instead i wanna do :
```php
$image = Image::newFromFile(storage_path('image.png') ', ['access' => 'sequential']);
$image = $image->crop(0,0,100,100);
return response()->file($image->path());
```

this is a serious problem for me and my app because of performance stuff
is there any way to do that or similar things?

**Comment by Mohammad-Khazaee** [comment]
seems there is a solution in sharp node js
https://stackoverflow.com/questions/65740056/how-to-send-the-resized-image-from-sharp-back-to-user

**Comment by jcupitt** [comment]
Hi @Mohammad-Khazaee, 

You can use `writeToBuffer` to write to a string, for example (untested):

```php
$data = $image->writeToBuffer(".jpg");
echo "Content-length: {strlen($data)}";
echo "Content-type: image/jpeg";
echo "";
echo $data;
```

**Comment by jcupitt** [comment]
See https://libvips.github.io/php-vips/classes/Jcupitt-Vips-Image.html#method_writeToBuffer

**Comment by Mohammad-Khazaee** [comment]
thanks for quick response
