### ISSUE TITLE
Version incompatibility with VIPS < 8.9.0 - FFI\Exception: Failed resolving C function 'vips_error_buffer_copy' in /app/app/vendor/jcupitt/vips/src/FFI.php:731

### ISSUE THREAD

**Issue by Waschnick** [libvips/php-vips#162]
Hey! My issue is actually the same as #145, but I can't resolve it.

### Error Message
```
[SYSLOG] [333]: [172.18.0.1][-][-][error][FFI\Exception] FFI\Exception: Failed resolving C function 'vips_error_buffer_copy' in /app/app/vendor/jcupitt/vips/src/FFI.php:731
[SYSLOG] [333]: Stack trace:
[SYSLOG] [333]: #0 /app/app/vendor/jcupitt/vips/src/FFI.php(731): FFI::cdef('// we need the ...', 'libvips.so.42')
```

### System
* Docker with PHP 7.4, Debian GNU/Linux 10
* vips working on the command line
* Vips version: vips-8.7.4-Sat Nov 21 16:50:57 UTC 2020
* php-vips installed via composer

I'm just trying to call `$image = Vips\Image::thumbnail('../some-image.svg', 128);`

### Steps I tried
* I tried to install vips with apt and also downloaded and build it myself - the issue is the same. I also tried the re-install mentioned in #145 
* I debugged FFI.php from php-vips, the library can be found
* The issue happens in FFI.php line 731

AFAIK this means that vips_error_buffer_copy is not available in the loaded C-ABI library. **From the [release logs](https://abi-laboratory.pro/index.php?view=changelog&l=vips&v=8.11.2) of vips that method was added in VIPS 8.9.0, but your documentation says php-vips is for vips 8.7**. For me this looks like a version mismatch.

**Comment by jcupitt** [comment]
Hi @Waschnick,

Thanks for the report -- this sounds like a bug. 

It doesn't look like this function was ever used, so I think you can just delete the line in FFI.php. Does that fix this issue?

**Comment by jcupitt** [comment]
... I made a tiny PR for this. Any testing would be great.

**Comment by jcupitt** [comment]
OK, merged to master. Thanks!
