### ISSUE TITLE
AVIF file size is bigger than it's WebP equivalent

### ISSUE THREAD

**Issue by sadektouati** [libvips/php-vips#175]
Here's the code I use,
`require_once('vendor/autoload.php');
    use Jcupitt\Vips;
    $image = Vips\Image::thumbnail(ORIGINAL_FILEPATH, $width, ['height' => 10000]);
    $image->writeToFile(FULL_FILEPATH);
`
Why every single AVIF file has a bigger size than webp?

And also I noticed that Gmagick is a lot faster, which is ironic for me. What I'm doing wrongly?

**Comment by jcupitt** [comment]
Hi @sadektouati,

You'll need to share some more details so I can reproduce the problem. What versions of libwebp and which AVIF encoder are you using? What platform? How did you compile them? What type of image?

With libvips 8.13 on ubuntu 22.10 (libaom 3.4, libwebp 1.22) and this photo:

http://www.rollthepotato.net/~john/nina.jpg

I see:

```
$ time vips copy nina.jpg x.webp

real	0m1.516s
user	0m1.479s
sys	0m0.080s
$ time vips copy nina.jpg x.avif

real	0m4.298s
user	0m15.163s
sys	0m0.264s
```

And with imagemagick (my GM isn't set up for AVIF encode):

```
$ time convert nina.jpg x-im.webp

real	0m1.604s
user	0m1.483s
sys	0m0.120s

$ time convert nina.jpg x-im.avif

real	0m4.323s
user	0m16.249s
sys	0m0.332s
```

Then:

```
$ ls -l x* 
-rw-r--r-- 1 john john 182686 Nov 28 08:59 x.avif
-rw-rw-r-- 1 john john 164884 Nov 28 09:00 x-im.avif
-rw-rw-r-- 1 john john 434312 Nov 28 09:00 x-im.webp
-rw-r--r-- 1 john john 434330 Nov 28 08:59 x.webp
```

So speed is about the same, though of course 99% of CPU is being spent in the same libraries, so you'd expect them to be very similar.

**Comment by jcupitt** [comment]
Could you run those commands on that test image and post the results please.

**Comment by jcupitt** [comment]
Sorry, it sounds like something has gone wrong with your rpm install. I'd ask on the remi repository.
