### ISSUE TITLE
Allow `psr/log` v2 and v3 in v1.x branch

### ISSUE THREAD

**Issue by PabloKowalczyk** [libvips/php-vips#176]
Hello, is it possible to allow newer `psr/log` in `1.x` branch?
I know that ` php-vips-ext` is deprecated, but using global FFI version without preload have performance and security impact, allowing newer `psr/log` on `1.x` branch will allow projects to still use PECL version while waiting for preloaded v2.
I could provide a PR.

**Comment by jcupitt** [comment]
Hi @PabloKowalczyk,

Sure, a PR would be great, thanks!

**Comment by PabloKowalczyk** [comment]
Turns out that the work was done before https://github.com/libvips/php-vips/commit/9080e310919285e4509d0564954c8c7468f84f06 and only missing piece is new release of v1, is it possible?

**Comment by jcupitt** [comment]
I had a go. Would you mind testing?

**Comment by PabloKowalczyk** [comment]
Works, thank you.
