### ISSUE TITLE
Sharpen images

### ISSUE THREAD

**Issue by sadektouati** [libvips/php-vips#177]
Hi @jcupitt 
Thanks for your help, and please bear with me, I have some questions.

1 How do you sharpen images (avif)? the equivalent of  Imagick::sharpenImage().

2 Any other optimisation is welcome.

3 I have a script that creates images on demand, when I create an image then I read it with file_get_contents() it does not send an image file (or at least so it looks to me) to the browser, instead the file is a bunch of gibberish characters. why? and how could I "echo" the resulting image without reading the created file?

**Comment by jcupitt** [comment]
Hello @sadektouati,

There's a dedicated sharpen operation here:

https://www.libvips.org/API/current/libvips-convolution.html#vips-sharpen

For more speed you could do a simple 3x3 laplacian. It depends on the quality you need.

You'd need to share some sample code before I could suggest bugfixes or improvements.

**Comment by jcupitt** [comment]
Have a look at the docs above ^^^ It's usually best to adjust the degree of sharpening with the `m2` parameter. If you are experimenting, nip2 is very useful:

https://github.com/libvips/nip2

You can adjust all the settings with sliders and watch pixels change.

![image](https://user-images.githubusercontent.com/580843/206138731-7c0d98be-5de4-45dd-afad-cd77ade6ba40.png)

php-vips is a dynamic binding, so it implements very little functionality itself, it just exposes the API it finds in the libvips binary it opens at runtime.

`sharpen` is defined in C here:

https://github.com/libvips/libvips/blob/master/libvips/convolution/sharpen.c
