### ISSUE TITLE
502 Bad Gateway Error after upgrade

### ISSUE THREAD

**Issue by johnvoncolln** [libvips/php-vips#180]
This just started happening intermittently after I upgraded the production server to jcupitt/vips 2.1.1

After a user uploads an image:

```php
$rawFile = Storage::disk('private')->putFileAs('', $request->file, $name);
$image = VipsImage::newFromFile(Storage::disk('private')->path($rawFile));
```

I'm logging right after this and when I get the 502 error, It doesn't hit the log.

I can refresh the page and half the time it will work, half the time 502 error.

Any ideas? Any other means of debugging?

**Comment by jcupitt** [comment]
Hi @johnvoncolln,

libvips has no built-in networking code, so I'd guess the problem is in `Storage::`

**Comment by johnvoncolln** [comment]
Hmm ok, I'll dive deeper into that area - thanks!

**Comment by goldmerc** [comment]
I'm having the same issue after upgrading to jcupitt/vips 2.1.1. 

@johnvoncolln Did you ever get to the bottom of this?

Thanks

**Comment by johnvoncolln** [comment]
@goldmerc I'm sorry I don't remember what I did. I've had a lot of grief getting vips to work on my local environment, but I eventually get it worked out. I'm using Laravel Valet, so I want to say this issue was there. I think I installed the new version and maybe that did the trick...
