### ISSUE TITLE
Usage troubles under Windows

### ISSUE THREAD

**Issue by West14** [libvips/php-vips#183]
Hello!

I'm trying to use your library under Windows 10, but there are few problems that I can't figure out how to solve.

1. ["The printf check"](https://github.com/libvips/php-vips/blob/ff7cb36fde54887ca61647b3ff76598caa69bd25/src/FFI.php#L204-L209) fails. It can't find `printf` function.
```
An exception occurred: [FFI\Exception] Failed resolving C function 'printf' in src\addons\Bubuni\LibVips\vendor\jcupitt\vips\src\FFI.php on line 208
#0 src\addons\Bubuni\LibVips\vendor\jcupitt\vips\src\FFI.php(208): FFI::cdef('    int printf(...')
#1 src\addons\Bubuni\LibVips\vendor\jcupitt\vips\src\FFI.php(116): Jcupitt\Vips\FFI::init()
#2 src\addons\Bubuni\LibVips\vendor\jcupitt\vips\src\VipsOperation.php(80): Jcupitt\Vips\FFI::vips()
#3 src\addons\Bubuni\LibVips\vendor\jcupitt\vips\src\VipsOperation.php(225): Jcupitt\Vips\VipsOperation::newFromName('black')
#4 src\addons\Bubuni\LibVips\vendor\jcupitt\vips\src\Image.php(1290): Jcupitt\Vips\VipsOperation::callBase('black', NULL, Array)
#5 test.php(28): Jcupitt\Vips\Image::__callStatic('black', Array)
#6 {main}
```
When I comment it, things start to work.

I also want to ask: what is the latest supported libvips version? When i try 8.14. I get errors like this.
![image](https://user-images.githubusercontent.com/30056636/214163680-65ad57e4-af1f-47de-bd1c-c7d945fa1669.png)
![image](https://user-images.githubusercontent.com/30056636/214163760-f0ed13ff-4eac-4118-b1c1-b32912ff3a8e.png)

I tried 8.13, but it does not give the expected result (I'll attach reproduce example if needed).
libvips 8.9 seems to be fine.

PHP version:
```# php -v
PHP 7.4.27 (cli) (built: Dec 14 2021 19:52:13) ( ZTS Visual C++ 2017 x64 )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Xdebug v3.1.6, Copyright (c) 2002-2022, by Derick Rethans
```

**Comment by jcupitt** [comment]
Hi @West14,

Thanks for reporting this. That's odd, I'd expect ffi to find `printf` in your C runtime. I have a win10 VM here, I'll fire it up and try it.

**Comment by jcupitt** [comment]
> When i try 8.14. I get errors like this.

I tried here and it seems to work. I downloaded:

https://github.com/libvips/build-win64-mxe/releases/download/v8.14.1/vips-dev-w64-web-8.14.1.zip

Then:

```
jcupi@DESKTOP-HGI6HBR MINGW64 /f/Downloads
$ unzip -qq vips-dev-w64-web-8.14.1.zip

jcupi@DESKTOP-HGI6HBR MINGW64 /f/Downloads
$ cd vips-dev-8.14/bin/

jcupi@DESKTOP-HGI6HBR MINGW64 /f/Downloads/vips-dev-8.14/bin
$ ./vips.exe black x.png 10 10

jcupi@DESKTOP-HGI6HBR MINGW64 /f/Downloads/vips-dev-8.14/bin
$
```

What did you download and how did you install it?

**Comment by West14** [comment]
`./vips.exe black x.png 10 10`

Problems occur when using PHP bindings. The CLI utility works fine and I have no issues with it.

**Comment by jcupitt** [comment]
So therefore I think it must be problem with the way you've installed libvips under php. You must have several different versions of eg. `libglib-2.0.dll` on your PATH, with an older one overriding the more recent version that libvips needs. It's quite a common library, so I expect you have installed some other package that also bundles it.

**Comment by jcupitt** [comment]
Ah it looks like php-vips 2.1.0 is missing the `printf()` test, you could try that.

**Comment by jcupitt** [comment]
I added the platform check to php-vips master.

> I tried 8.13, but it does not give the expected result (I'll attach reproduce example if needed).

Yes please, it'd be interesting to see what failed.

**Comment by West14** [comment]
> So therefore I think it must be problem with the way you've installed libvips under php. You must have several different versions of eg. `libglib-2.0.dll` on your PATH, with an older one overriding the more recent version that libvips needs. It's quite a common library, so I expect you have installed some other package that also bundles it.

Hm. Thanks for the hint. Thats it!
My web-server software uses separate PATH and there was one `libglib-2.0-0.dll` in the nginx package.
![image](https://user-images.githubusercontent.com/30056636/214345356-52d2d35a-0eae-46d4-b8c4-479947d2ffc1.png)

Thank you very much! 

> Yes please, it'd be interesting to see what failed.
I will check it again and post here. Now I'm not sure I did the test right.

**Comment by West14** [comment]
> I'll put an if(PHP_OS_FAMILY !== "Windows"){} around that.

Maybe [ini_get](https://www.php.net/manual/en/function.ini-get.php) can be used?
It seems OK.
![image](https://user-images.githubusercontent.com/30056636/214355443-1de69354-ad3d-41c7-a9bd-4bc8a36d622f.png)

So we can just do the check like this:
```php
strtolower(ini_get('ffi.enable')) == 'true'
```

**Comment by jcupitt** [comment]
Oh nice! I've added that and credited you.

**Comment by West14** [comment]
I'm trying to find out a way how to check it easily.

This is how PHP determines if INI value is `true`, so perhaps a similar check could be implemented in the library?
https://github.com/php/php-src/blob/ec23f28ea8549f5c4ddbcb9c48728e82d5219ba8/Zend/zend_ini.c#L573-L583

And, of course, we must not forget about the "preload" option, which is currently not supported as far as I know.

**Comment by West14** [comment]
We can simply check for the existence of the FFI class.
i.e. 
```php
class_exists('FFI')
```

**Comment by jcupitt** [comment]
I tried the various values with php 8.1. I see:

```
# ffi.enable=true
$ php -r "var_dump(ini_get('ffi.enable'));"
string(1) "1"
# ffi.enable=false
$ php -r "var_dump(ini_get('ffi.enable'));"
string(0) ""
# ffi.enable=preload
$ php -r "var_dump(ini_get('ffi.enable'));"
string(7) "preload"
```

Sadly it seems the way ini variable values are represented changes quite a bit with the php version :( 

> And, of course, we must not forget about the "preload" option, which is currently not supported as far as I know.

Yes, it'd be good to support preload, but no one's done the work yet.

**Comment by SerafimArts** [comment]
You can use a simple library to check the availability of FFI: https://github.com/php-ffi/env Or just take the FFI check source code from there.

Sorry for the ad =)))

**Comment by jcupitt** [comment]
Oh nice! Thanks for the link @SerafimArts.

I don't suppose you know how to detect FFI set to preload?

**Comment by SerafimArts** [comment]
> I don't suppose you know how to detect FFI set to preload?

```
$isPreload = ini_get('ffi.enable') === 'preload';
```

In addition, note that `preload` is completely equivalent to `true` (enabled) in CLI mode.

**Comment by jcupitt** [comment]
I noticed you have:

```
        // - Returns "1" in case of 'ffi.enable=true' or 'ffi.enable=1' in php.ini
        // - Returns "" (empty string) in case of 'ffi.enable=false' or 'ffi.enable=0' in php.ini
        // - Returns "0" in case of direct execution `php -dffi.enable=0 file.php`
        $config = \ini_get(self::EXT_CONFIG_NAME) ?: '0';
```

I think it can also be `"TRUE"`, at least under windows and with some php versions.

**Comment by jcupitt** [comment]
west14 was seeing `"TRUE"` on windows with openserver, see: https://github.com/libvips/php-vips/issues/183#issuecomment-1402273635

Though I don't know what php version that was.

**Comment by SerafimArts** [comment]
Yep, I saw it, but I didn’t manage to reproduce this case even if `TRUE` is written in capital letters.

But... Wait, there is one assumption related to the differences between NTS / TS

**Comment by SerafimArts** [comment]
No, there are no differences when running on PHP 7.4.33 TS

**Comment by SerafimArts** [comment]
P.P.S. However, it is true that the `printf` function does not exist on Windows and the library cannot be loaded. 

In addition, there are problems with finding the binary file (relations of libvips) due to the relative paths of the linker. To do this, you need to change `chdir` (on NTS) or call:
- `SetDllDirectoryA` from `kernel32.dll` on Windows PHP TS
- `setenv('LD_LIBRARY_PATH')`  on Linux/BSD PHP TS
- `setenv('DYLD_LIBRARY_PATH')`  on MacOS PHP TS

But that seems to be a separate issue and/or PR =)))

**Comment by West14** [comment]
> west14 was seeing `"TRUE"` on windows with openserver, see: [#183 (comment)](https://github.com/libvips/php-vips/issues/183#issuecomment-1402273635)
> 
> Though I don't know what php version that was.

It depends on the value in `php.ini`. Looks like `ini_get` prints the value "as is" if it's wrapped with quotes in the INI. This is the default value in the OpenServer.

**Comment by SerafimArts** [comment]
Yes indeed. If enclosed in quotation marks, then the `"TRUE"` output will be. However, this is an incorrect value and actually means "preload".

Sorry, my comment above (https://github.com/libvips/php-vips/issues/183#issuecomment-1420426084) was incorrect, did not take this case into account

**Comment by jcupitt** [comment]
This PR tries to improve library finding again, let's move discussion there.

https://github.com/libvips/php-vips/pull/206
