### ISSUE TITLE
Having trouble implementing brightness

### ISSUE THREAD

**Issue by axkirillov** [libvips/php-vips#193]
Hi!

I am trying to implement the following javascript algorithm in php-vips. It seems to me that the calculations are identical. But the result differs.
Here is the javascript
```

for (let i = 0; i < length; i += 4) {
  const avg = (r + g + b) / 765;
		
  const factor = 1 + (brightness * (1 - avg));
		
  r *= factor;
  g *= factor;
  b *= factor;
}
```
here is the php-vips version
```
$sum = $r->sum([$g, $b]);
$avg = $sum->linear(1 / (3 * 255), 0);
$factor = $avg->linear(-1 * $brightness, 1 + $brightness);
$r = $r->multiply($factor);
$g = $g->multiply($factor);
$b = $b->multiply($factor);
$imageResult = $r->bandjoin([$g, $b]);
```
Result fot -1 brightness:
js
![image](https://user-images.githubusercontent.com/32141102/226674601-cd664d34-ca2d-4328-9b0f-6a98f0f8b00c.png)
php-vips
![canvas_1679415206326](https://user-images.githubusercontent.com/32141102/226674761-64855cd6-e669-4aae-9d2a-fddf4169661e.jpg)

**Comment by axkirillov** [comment]
Figured it out, I was using ::sum incorrectly
the correct usage is as static function:
`$sum = Vips\Image::sum([$r, $g, $b]);`

**Comment by axkirillov** [comment]
Another thing that probably stems from me not understanding colorspaces and such is that when the original image is png, the following implementation also produces not quite expected result. I'll paste the entire code here since there might be smth relevant I am missing.
```php
		$start = microtime(true);
		$hasAlpha = $image->hasAlpha();

		// remove alpha, if any
		if ($hasAlpha) {
			$alpha = $image->extract_band($image->bands - 1, ['n' => 1]);
			$image = $image->extract_band(0, ['n' => $image->bands - 1]);
		}

		/** 
		 * @var Vips\Image $r 
		 * @var Vips\Image $g 
		 * @var Vips\Image $b 
		 * */
		[$r, $g, $b] = $image->bandsplit();
		$brightness = $this->brightness / 100;

		// equivalent javascript

		//for (let i = 0; i < length; i += 4) {
		//  const avg = (data[i] + data[i + 1] + data[i + 2]) / 765;
		//
		//  const factor = 1 + (valueToUse * (1 - avg));
		//
		//  data[i] *= factor;
		//  data[i + 1] *= factor;
		//  data[i + 2] *= factor;
		//
		// scrgb is linear 0-1 pixels, bandmean makes a one-band image by averaging bandwise

		$factor = $image->colourspace("scrgb")->bandmean()->linear(-1 * $brightness, 1 + $brightness);	//}
		$r = $r->multiply($factor);
		$g = $g->multiply($factor);
		$b = $b->multiply($factor);
		$image = $r->bandjoin([$g, $b]);

		// add alpha back
		if ($hasAlpha) {
			$image = $image->bandjoin($alpha);
		}

		$blob = $image->writeToBuffer($hasAlpha ? '.png' : '.jpg');
		$imagick = new \Imagick();
		$imagick->readImageBlob($blob);
``` 
Prior to this the image is simply loaded like this:
```php
Vips\Image::newFromBuffer($this->getRawContent($url));
``` 
expected (brightness  is 1)
<img width="670" alt="image" src="https://user-images.githubusercontent.com/32141102/226908361-a7608dc3-d931-4ca3-b147-91878c97d54c.png">
result
<img width="490" alt="image" src="https://user-images.githubusercontent.com/32141102/226908465-dd599415-e996-43eb-969e-3dc7a9541353.png">

**Comment by jcupitt** [comment]
> doing this however results in a different image than expected

Yes, it'll look a bit different.

sRGB images have a gamma, meaning that numeric values in the file have a power law relationship with brightness (usually 2.2). Converting to `scrgb` (note the `c`) makes an image with pixels in 0-1 and a linear relationship with light. Lightness adjustments made in the space should look more natural (ie. better).

If you prefer the gamma look, you can just do:

```php
$image = $image->divide(255);
```

instead.

**Comment by jcupitt** [comment]
So just write:

```php
		$brightness = $this->brightness / 100;

		// equivalent javascript

		//for (let i = 0; i < length; i += 4) {
		//  const avg = (data[i] + data[i + 1] + data[i + 2]) / 765;
		//
		//  const factor = 1 + (valueToUse * (1 - avg));
		//
		//  data[i] *= factor;
		//  data[i + 1] *= factor;
		//  data[i + 2] *= factor;
		//
		// scrgb is linear 0-1 pixels, bandmean makes a one-band image by averaging bandwise

		$factor = $image->colourspace("scrgb")->bandmean()->linear(-1 * $brightness, 1 + $brightness);
		$image = $image->multiply($factor);
```

**Comment by axkirillov** [comment]
Thank you for the suggestions!
Indeed, `divide(255)` works as expected for both png and jpg
`$image = $image->multiply($factor);` also works, I might have confused the two problems at first.
