### ISSUE TITLE
libvips can't find srgb profile

### ISSUE THREAD

**Issue by axkirillov** [libvips/php-vips#196]
Hi! I assumed that libvips has a buildtin srgb profile but when using it in php-vips im getting the error:
```
icc_transform: unable to open profile "srgb"
``` 
The code is simply:
```php
$image = $image->icc_transform('srgb');
``` 
The php-vips version is 2.1.1 the vips version is 8.12.1

**Comment by jcupitt** [comment]
Hi again, 

Yes, a set of builtin profiles were added in libvips 8.8.

Are you certain your php is picking up the right libvips at runtime? 

```php
echo Vips\Config::version();
```

Should show the library version that php has linked to.

**Comment by axkirillov** [comment]
You are correct, it shows 8.7.4. I'll investigate.

**Comment by axkirillov** [comment]
The problem was that I had the old vips php extension installed it seems like
