### ISSUE TITLE
Implementing BlurHash with php-vips

### ISSUE THREAD

**Issue by binaryfire** [libvips/php-vips#200]
Hi John

Is there any way to implement BlurHash with php-vips? 

https://blurha.sh/
https://github.com/woltapp/blurhash

There are a couple of PHP implementations. One is pure PHP, the other uses Intervention:
https://github.com/kornrunner/php-blurhash
https://github.com/bepsvpt/blurhash

I'm using vips to generate responsive images for my users' uploads and would love to generate a BlurHash at the same time. They're an amazing alternative to placeholder images.

**Comment by jcupitt** [comment]
You could use libvips for the initial shrink, but you'd need to code the DCT yourself (not difficult). 

Maybe libvips for the preprocessing and php-blurhash as the encoder?

**Comment by binaryfire** [comment]
Thanks, will give that a shot!

**Comment by binaryfire** [comment]
Ended up going with a 16px base64 webp + CSS blur. Seems to do the trick and there's no special decoding step needed.

I'm using `thumbnail()` with Q=20 and reduction_effort=4. The base64-encoded images are under 200b which is great. But the contrast is a little washed out compared to original.

Does thumbnail() have any image processing options that might help? Or should I be using a different method?

Performance is my main concern. It's a multi-tenant media library and I'm already generating 5-6 webp size variants on upload.

**Comment by jcupitt** [comment]
`thumbnail` is resize only, but you can combine it with other operations, of course. Perhaps a strong sharpening filter after the resize would improve contrast?

php-vips is usually fast enough that you can generate size variants on the fly and don't need to produce them at upload time. Your clients will get images exactly sized for their screen, and you save a lot on storage costs. CPU is often cheaper and faster than storage now. You could perhaps only compute the blurhash at upload time and leave image generation until later.

```
$ vipsheader nina.jpg
nina.jpg: 6048x4032 uchar, 3 bands, srgb, jpegload
$ /usr/bin/time -f %M:%e vipsthumbnail nina.jpg
40448:0.06
```

60ms and 40mb of ram to resize a 6k x 4k pixel jpeg, and that's with process startup time.

**Comment by binaryfire** [comment]
Nice. I was considering doing it on-demand but I’m using webp, which is a lot slower than jpg. I’ll do some tests though. Maybe it’ll be fine.

**Comment by jcupitt** [comment]
Ah, you're using webp for all the derivatives? I agree, that's probably too slow.

**Comment by binaryfire** [comment]
Thanks for your help and suggestions! I'll close this now.
