### ISSUE TITLE
PHP 8.3 Statically Deprecated Message

### ISSUE THREAD

**Issue by sr-oct** [libvips/php-vips#226]
I've encountered a "PHP Deprecated" warning while running tests with PHPUnit 9.6.13, specifically under PHP 8.3. This might be indicative of compatibility issues that could arise with the new PHP version.

Thought it’d be useful to flag this up for potential updates or fixes.

```shell
PHP Deprecated:  Calling FFI::cast() statically is deprecated ... vendor/jcupitt/vips/src/Image.php on line 503
...jcupitt/vips/src/VipsObject.php on line 71
```

Appreciate all your work on this library!

**Comment by dmitryuk** [comment]
#231

**Comment by dmitryuk** [comment]
@jcupitt can you make a new release?

**Comment by jcupitt** [comment]
Hi again, yes, I'm planning to, we just need to fix the CI failure.
