### ISSUE TITLE
How do I avoid using static access to class '\Jcupitt\Vips\Image'?

### ISSUE THREAD

**Issue by BadgerCat1066** [libvips/php-vips#244]
I think VIPS is brilliant and easy to use, however, PHPMD (Mess Detector) flags up _'Avoid using static access to class \Jcupitt\Vips\Image'_ when I am writing a line such as:

$im = Vips\Image::newFromFile($file);

Is there any way of using a factory in the constructor to instatiate VIPS and load an image in a way that PHP MD will not complain about? Or even 'new Vips/Image'?

**Comment by kleisauke** [comment]
PHP MD is likely too strict in this case. As per https://phpmd.org/rules/cleancode.html#staticaccess, it states:
> [...] The only case when static access is acceptable is when used for factory methods.

I think the static `Image::newFrom*` methods qualifies as a factory method. You can use the following rule set to ignore these warnings: 
```xml
    <rule ref="rulesets/cleancode.xml/StaticAccess">
        <properties>
            <property name="ignorepattern" value="/^newFrom/i" />
        </properties>
    </rule>
```
See: https://phpmd.org/documentation/creating-a-ruleset.html.
