### ISSUE TITLE
Can this support make png file which has transparent alpha to a transparent pdf file

### ISSUE THREAD

**Issue by jonny77** [libvips/php-vips#249]
require __DIR__ . '/vendor/autoload.php';
use Jcupitt\Vips;

$image = Vips\Image::newFromFile('./images/demo.png', ['access' => 'sequential']);

$image->writeToFile('./aa.pdf', [
    //'format' => 'pdf'
]);
not working and got error 
VipsForeignSave: "./aa.pdf" is not a known file format

**Comment by jcupitt** [comment]
Sorry, libvips does not support PDF write.
