### ISSUE TITLE
Loading TTF fonts at runtime

### ISSUE THREAD

**Issue by olivervogel** [libvips/php-vips#254]
I have problems rendering text with a TTF font onto an image.

As far as I can see from [this comment](https://github.com/libvips/libvips/issues/950#issuecomment-384772448), with python it is possible to load fonts from files at runtime using the `fontfile` option. However, when I try to transfer the code to PHP this does not seem to work, the text does not appear in the correct font.

I have already tried the following.

- Absolute specification of the TTF path
- Changing the font name in the `font` option
- Using the `LoversQuarrel-Regular.ttf ` TTF from the comment

Does anyone have an idea what could be wrong here?

### Code example

```php
use Jcupitt\Vips\BandFormat;
use Jcupitt\Vips\Extend;
use Jcupitt\Vips\Image;
use Jcupitt\Vips\Interpretation;

$canvas = Image::black(1, 1)
    ->add(60)
    ->cast(BandFormat::UCHAR)
    ->embed(0, 0, 500, 500, ['extend' => Extend::COPY]) // 500x500 px canvas
    ->copy(['interpretation' => Interpretation::SRGB])
    ->bandjoin([
        60, // green
        60, // blue
        255, // alpha
    ]);

$text = Image::text('Test!', [
    'fontfile' => './Impact.ttf',
    'font' => 'Impact 16',
    'dpi' => 300,
]);

$textImage = $text->newFromImage([255, 120, 0])
    ->copy(['interpretation' => Interpretation::SRGB])
    ->bandjoin($text);

$modified = $canvas->composite($textImage, 'over', [
    'x' => 100,
    'y' => 100,
]);

$encoded = $modified->writeToBuffer('.png');

```

### Result image

![vips](https://github.com/user-attachments/assets/8c150d64-f9aa-411c-88ab-cd0a8c31ec0b)

### Environment

PHP 8.4
libvips 8.16.0
jcupitt/vips 2.4.0

**Comment by jcupitt** [comment]
Hi again, it should work. What platform is this? Runtime font loading depends on fontconfig, I believe.

You can make your test program a little simpler:

```php
#!/usr/bin/env php
<?php

require __DIR__ . '/vendor/autoload.php';
use Jcupitt\Vips;

$image = VIps\Image::black(1, 1)
    ->add([60, 60, 255])
    ->cast(Vips\BandFormat::UCHAR)
    ->embed(0, 0, 500, 500, ['extend' => Vips\Extend::COPY])
    ->copy(['interpretation' => Vips\Interpretation::SRGB]);

$text = Vips\Image::text('<span foreground="#ff8000">Test!</span>', [
    'fontfile' => $argv[2],
    'font' => $argv[3],
    'dpi' => 300,
    'rgba' => true,
]);

$image = $image->composite($text, 'over', [
    'x' => 100,
    'y' => 100,
]); 
    
$image->writeToFile($argv[1]);
```

With this font file:

[Miss_Fajardose.zip](https://github.com/user-attachments/files/18269404/Miss_Fajardose.zip)

I can run:

```
$ ./text.php x.png /home/john/pics/PT_Serif-Web-BoldItalic.ttf MissFajardose
```

And I get the right font.

**Comment by olivervogel** [comment]
Thanks @jcupitt.

I have tried it again with your script. Unfortunately without success. I'm running MacOS 14, PHP 8.4 and the vips library mentioned above.

The script still renders a generic font.
![vips](https://github.com/user-attachments/assets/e5533ff2-e4dc-4a53-a79f-e13b9dde1c76)

**Comment by jcupitt** [comment]
Ah OK, that's a macOS issue (I think). libvips is using pangocairo to render text, and on macOS (I hope I have this right) it's not using freetype2 (the usual linux font rendering system), instead it's using Quartz, the macOS renderer. This doesn't support runtime font loading with the fontconfig API.

I may have this completely mixed up :( Text rendering is horribly complicated. 

I would install linux in a VM and develop for that, unless you have to deploy on macOS.

**Comment by olivervogel** [comment]
> [...] Quartz, the macOS renderer [...] doesn't support runtime font loading with the fontconfig API.

Okay thanks, that's a bummer.

**Comment by kleisauke** [comment]
Note that you could set the `PANGOCAIRO_BACKEND="fontconfig"` environment variable on macOS to ensure fontconfig is used for font discovery instead of CoreText. Context: https://github.com/lovell/sharp/issues/2399.

**Comment by jcupitt** [comment]
Ah interesting, I didn't know that. Thanks Kleis.
