### ISSUE TITLE
Runtime configuration using php.ini

### ISSUE THREAD

**Issue by kleisauke** [libvips/php-vips#35]
It would be nice to change the cache, concurrency, or disc threshold settings of libvips (without touching the code) using `php.ini`.

We could do something like this:
![vipsinfo](https://cloud.githubusercontent.com/assets/12746591/23130452/bd5e7f94-f786-11e6-9be7-50a906758d8d.png)

It's then easy to adjust libvips settings with `php.ini`:
```ini
# Can take a unit postfix of "k", "m" or "g" to indicate kilobytes, megabytes or gigabytes (default 100mb)
vips.disc_threshold = 100mb
# 0 = default (the number of threads available on the host machine)
vips.concurrency = 0
# The maximum number of operations to cache (default 1000 operations)
vips.cache_max = 100
# The maximum memory in MB to use for this cache  (default 50mb)
vips.cache_max_mem = 50
# The maximum number of files to hold open (default 20 files)
vips.cache_max_files = 20
```

Or using [ini_set](http://php.net/manual/en/function.ini-set.php) in PHP:
```php
// Can take a unit postfix of "k", "m" or "g" to indicate kilobytes, megabytes or gigabytes (default 100mb)
ini_set('vips.disc_threshold', '100mb');
// 0 = default (the number of threads available on the host machine)
ini_set('vips.concurrency', 0);
// The maximum number of operations to cache (default 1000 operations)
ini_set('vips.cache_max', 100);
// The maximum memory in MB to use for this cache  (default 50mb)
ini_set('vips.cache_max_mem', 50);
// The maximum number of files to hold open (default 20 files)
ini_set('vips.cache_max_files', 20);
```

If this is implemented, we could drop (in my opinion) some of the functions in the [`\Jcupitt\Vips\Config`](https://github.com/jcupitt/php-vips/blob/master/src/Config.php#L89-L141) class.  (I think it's unnecessary, to adjust settings with the `Config class` if it is also configurable with `ini_set`).

Useful links (for implementation):
https://github.com/php/php-src/blob/PHP-7.1.1/ext/gd/gd.c#L993-L997
https://github.com/php/php-src/blob/PHP-7.1.1/ext/gd/gd.c#L1268
https://github.com/php/php-src/blob/PHP-7.1.1/ext/gd/gd.c#L2405

**Comment by kleisauke** [comment]
We can also add environment variables (such as `VIPS_WARNING` and `VIPS_INFO`) to the `php.ini`. This to suppress warning messages or to show info messages (useful for debugging purposes).

**Comment by dmitryuk** [comment]
I think it's impossible, because the project is not a php extenstion, it uses only FFI.

Please close

**Comment by kleisauke** [comment]
This problem was opened on php-vips 1.x at the time,  where it utilized https://github.com/libvips/php-vips-ext.

It would still be possible to do this during [`FFI::init()`](https://github.com/libvips/php-vips/blob/85affa54a16aa8a0b292e7e99945a14826b2650f/src/FFI.php#L230) by using [`ini_get()`](https://www.php.net/manual/en/function.ini-get.php), but that's probably a bit unusual. I'll close.
