### ISSUE TITLE
Jcupitt\Vips\Exception: VipsJpeg: out of order read at line 600

### ISSUE THREAD

**Issue by snoopy2010** [libvips/php-vips#67]
Hi,

using: pecl vips 1.0.8 with r1.0.2 @ php v7.0.27
on resizing 100000 images i get about 1000 errors.
i run up to 8 threads parallel.

```php
             $image=Vips\Image::newFromBuffer($media_buffer);
              if ($orientation=="1" AND $image->width>1200) {
               $image=Vips\Image::thumbnail_buffer($media_buffer, 1200);
              }
              if ($orientation=="2" AND $image->width>800) {
                $image=Vips\Image::thumbnail_buffer($media_buffer, 800);
              }
              $image->writeToFile($storepath."/1/".$mediabasename); 

              if ($orientation=="1" AND $image->width>495) {
                $image=Vips\Image::thumbnail_buffer($media_buffer, 495);
              }
              if ($orientation=="2" AND $image->width>330) {
                $image=Vips\Image::thumbnail_buffer($media_buffer, 330);
              }
              $image->writeToFile($storepath."/2/".$mediabasename); 
              if ($orientation=="1" AND $image->width>240) {
                $image=Vips\Image::thumbnail_buffer($media_buffer, 240);
              }
              if ($orientation=="2" AND $image->width>160) {
                $image=Vips\Image::thumbnail_buffer($media_buffer, 160);
              }
              $image->writeToFile($storepath."/3/".$mediabasename); 
              $image=Vips\Image::thumbnail_buffer($media_buffer, 55, ["height" => 55]);
              $image->writeToFile($storepath."/4/".$mediabasename);  
```

anyone an idea?
thx!
Snoopy

```
Jcupitt\Vips\Exception: VipsJpeg: out of order read at line 600
VipsJpeg: out of order read at line 600
 in /var/cron_fmh/pmedia/vendor/jcupitt/vips/src/Image.php:664
Stack trace:
#0 /var/cron_fmh/pmedia/vendor/jcupitt/vips/src/Image.php(865): Jcupitt\Vips\Image::errorVips()
#1 /var/cron_fmh/pmedia/iprc.php(254): Jcupitt\Vips\Image->writeToFile('/data/x3/155...')
#2 {main}
```

**Comment by jcupitt** [comment]
Hi Snoopy,

Sorry to hear you're having problems. Could you give some more information please?

- which version of libvips
- what platform (Linux, Windows etc.)
- how did you build it
- are the failures random, or do some images always fail

8.5.4 had a fix for an out of order bug, so if you're using a libvips older than that, upgrading might help.

**Comment by jcupitt** [comment]
As a workaround, you could disable threading. It doesn't actually help much for thumbnailing. Add this:

```php
Vips\Config::concurrencySet(1);
```

https://jcupitt.github.io/php-vips/docs/classes/Jcupitt.Vips.Config.html#method_concurrencySet

**Comment by snoopy2010** [comment]
Hi John,
thank you for your fast answer! I will try you suggestion.

I am using:
libvips 8.6.2-Wed Jan 31 20:39:14 UTC 2018
PHP 7.0.27-1+0~20180114070440.15+jessie~1.gbp3bc0e2 
debian 8.10

>>how did you build it?
get project from github, unpack
configure, make && make install (ended with no errors)
PHP: pecl install vips and checked vips.so in php.ini files.

most of the failures are the same and occur always on jpeg-images which have portrait mode (160x600px).

i will make the test with your suggestion and will post the results.
what i can say: i changed the php syntax from mkdir() to shell_exec("mkdir -p..."). the error-rate goes down to about 50%. i tested it twice to be sure that it´s no coincidence.

**Comment by snoopy2010** [comment]
Hi,
just tried Vips\Config::concurrencySet(1);
i got many write errors. So I  also implement a check if the path is writeable before executing 
$image->writeToFile($storepath."/s3/".$mediabasename); 

if (is_writable($storepath."/s3/")) {....}
The path exists for sure!

cupitt\Vips\Exception: vips__file_open_write: unable to open file "/data/x3/36080/s3/B43qM24y63H.jpg" for writing
unix error: No such file or directory
 in /var/cron_fmh/pmedia/vendor/jcupitt/vips/src/Image.php:664

Any idea?

Helmut

**Comment by jcupitt** [comment]
Hello Helmut, sorry, this dropped off my radar. 

No, I don't know why you are getting a "no such file" error. Could the directory be being deleted between the test and the write?

**Comment by jhony1104** [comment]
Maybe (this)[https://github.com/libvips/ruby-vips/issues/109#issuecomment-304611975] is related?

**Comment by jcupitt** [comment]
Helmut's libvips included that fix, so it's probably not the same issue.

This issue is probably all out of date now. I'll close, please open a new issue if there is a problem with current libvips.
