### ISSUE TITLE
VipsOperation: class "composite2" not found

### ISSUE THREAD

**Issue by wyatt121** [libvips/php-vips#76]
Hi John,

I hope all is well.  I have installed your PHP-VIPs on an additional server.  I was very happy to get your software installed very easily the second time.   But, unfortunately, I still ran into an issue.  

When I run my script on this new server, I get this error:

PHP Fatal error:  Uncaught Jcupitt\Vips\Exception: VipsOperation: class "composite2" not found
 in /var/www/html/hta_mockups/vendor/jcupitt/vips/src/Image.php:664
Stack trace:
#0 /var/www/html/hta_mockups/vendor/jcupitt/vips/src/Image.php(685): Jcupitt\Vips\Image::errorVips()
#1 /var/www/html/hta_mockups/vendor/jcupitt/vips/src/Image.php(1052): Jcupitt\Vips\Image::errorIsArray(-1)
#2 /var/www/html/hta_mockups/vendor/jcupitt/vips/src/Image.php(1130): Jcupitt\Vips\Image::callBase('composite2', Object(Jcupitt\Vips\Image), Array)
#3 /var/www/html/hta_mockups/mockup.php(94): Jcupitt\Vips\Image->__call('composite2', Array)
#4 {main}
  thrown in /var/www/html/hta_mockups/vendor/jcupitt/vips/src/Image.php on line 664

Do I have an outdated version of Php-Vips installed?  I'm not sure how to proceed.

Any help is much appreciated.

Regards,

Wyatt

**Comment by jcupitt** [comment]
Hello, I'd guess your libvips is too old. Do you know what version you are using?

**Comment by wyatt121** [comment]
Hi John,

I had libvips42 (8.2.2-1), installed on Ubuntu 16.04.  I'm assuming this is
too old.  I will download and compile from source.

Wyatt

**Comment by jcupitt** [comment]
Hopefully this is resolved -- I'll close.
