### ISSUE TITLE
Watermark image opacity

### ISSUE THREAD

**Issue by rahilwazir** [libvips/php-vips#78]
Is there a way to adjust the opacity/density of the watermark image? In my case `blend => true` is barely visible. And when doing `blend => false` its very dense.

Using the following code: https://github.com/jcupitt/php-vips/issues/40#issuecomment-292833750

**Comment by jcupitt** [comment]
Just scale the alpha down. In that program, change these lines:

```php
$watermark_alpha = $watermark[$watermark->bands - 1];
$watermark = $watermark->extract_band(0, ['n' => $watermark->bands - 1]);

// the main image can have an optional alpha ... we need to remove this before
// we blend the watermark in, we don't want to change the main image alpha
```

to be:

```php
$watermark_alpha = $watermark[$watermark->bands - 1];
$watermark = $watermark->extract_band(0, ['n' => $watermark->bands - 1]);

$watermark_alpha = $watermark_alpha->multiply(0.5); 

// the main image can have an optional alpha ... we need to remove this before
// we blend the watermark in, we don't want to change the main image alpha
```

**Comment by jcupitt** [comment]
I see:

![x](https://user-images.githubusercontent.com/580843/44513217-a8bbbc80-a6b4-11e8-906c-870053d2db8b.jpg)

**Comment by rahilwazir** [comment]
Thank you!

The `->multiply()` method worked nicely. However, the `composite` method messed up actually. It blacked out the input image and only watermark overlay is visible.

`multiply` with `embed` method

![image](https://user-images.githubusercontent.com/1818941/44529888-9cf8e600-a706-11e8-9421-f6da4f0df654.png)

`multiply` with `composite` method

![image](https://user-images.githubusercontent.com/1818941/44529588-ea288800-a705-11e8-9dba-526064227de6.png)

And by the way, please I don't want to repeat the overlay and center align it as well. That was possible with the `embed($top, $left, ...)` method, how can I achieve this with `composite`?

vips: `8.6.5`
PHP: `7.2.8`

**Comment by rahilwazir** [comment]
@jcupitt Please download the images from here: https://drive.google.com/drive/folders/1mknuYnn9mtHTm0RFQRGLaoLmJg1nNtT2

> just change the replicate lines near the top to match what you had before.

Sure, but does it not possible with the `composite` method?

**Comment by jcupitt** [comment]
Oh dear, this slipped a bit, sorry. I made this:

```php
#!/usr/bin/env php
<?php

require __DIR__ . '/vendor/autoload.php';
use Jcupitt\Vips;

if(count($argv) != 4) {
    echo("usage: ./watermark.php input-image output-image watermark-image\n");
    exit(1);
}

$image = Vips\Image::newFromFile($argv[1], ['access' => 'sequential']);
$output_filename = $argv[2];
$watermark = Vips\Image::newFromFile($argv[3], ['access' => 'sequential']);

// scale the watermark to 50% of the image width
$factor = 0.5 * $image->width / $watermark->width;
$watermark = $watermark->resize($factor);

// centre the watermark on the image
$left = ($image->width - $watermark->width) / 2;
$top = ($image->height - $watermark->height) / 2;

$final = $image->composite2($watermark, 'over', ['x' => $left, 'y' => $top]);

$final->writeToFile($output_filename);
```

It creates:

![x](https://user-images.githubusercontent.com/580843/49302165-31b96f80-f4be-11e8-95e5-8e01a69ca593.jpg)

**Comment by rahilwazir** [comment]
@jcupitt Ah superb, thanks!

Also why there are two methods `composite` and `composite2`?
