### ISSUE TITLE
Installing php-vips on Laravel Valet on Mac

### ISSUE THREAD

**Issue by johnvoncolln** [libvips/php-vips#85]
Sorry to have to ask here, but I've been search forever for a solution.  Having a bear of a time installing the php extension.  I've got vips installed:

```
$ vips -v
vips-8.7.4-Fri Jan 18 12:51:47 UTC 2019
```

but when I try `pecl install vips` I get this error below:

```
configure: error: you need at least libvips 8.2 for this module
ERROR: `/private/tmp/pear/temp/vips/configure --with-php-config=/usr/local/opt/php/bin/php-config --with-vips' failed
```

Hoping someone has seen this before and can help.

**Comment by johnvoncolln** [comment]
Looks like it's pretty much the same as [this issue](https://github.com/libvips/php-vips/issues/48)

**Comment by johnvoncolln** [comment]
Uninstalled libvips and ran `pecl install vips` again, and got the same error.  I also did a system wide search for 'vips' and 'libvips', not finding anything. So, I'm thinking that pecl is looking in the wrong place for vips, but not sure how to correct.

**Comment by jcupitt** [comment]
Hi @johnvoncolln, I guess you are using homebrew, is that right? Are you using homebrew php as well? I'm on holiday right now, but I'll be able to try on my mac at home by the end of the week.

**Comment by johnvoncolln** [comment]
Thanks for getting back to me @jcupitt - here are my specs:

PHP: 7.3.4
VIPS: 8.7.4

installed via homebrew.  It's possible that I had installed another version prior to this to play around with VIPS on cli.  I've uninstalled and reinstalled a few times with the same results.

**Comment by johnvoncolln** [comment]
@jcupitt Hi - did you ever get a chance to try that out?

**Comment by jcupitt** [comment]
Sorry @johnvoncolln, this slipped my mind with the Easter holidays.

I'll have a look now.

**Comment by jcupitt** [comment]
I think I found the problem. 

pecl uses pkg-config to find vips. Try:

```
$ pkg-config vips --cflags
Package libffi was not found in the pkg-config search path.
Perhaps you should add the directory containing `libffi.pc'
to the PKG_CONFIG_PATH environment variable
Package 'libffi', required by 'gobject-2.0', not found
```

Apple supply libffi, but they stupidly do not include the `.pc` files, so no one can use it. brew installs its own libffi, but they can't link you to it by default, since that would prevent you using the Apple one.

The trick is to point pkg-config to the homebrew libffi just for the pecl install. Try:

```
$ PKG_CONFIG_PATH=/usr/local/opt/libffi/lib/pkgconfig pecl install vips
```

and it should work.

**Comment by johnvoncolln** [comment]
Brilliant!  That worked - thank you.  Hopefully this will find some other folks who run into the same issue.
