### ISSUE TITLE
Vips Thumbnail - no known route from 'cmyk' to 'srgb'

### ISSUE THREAD

**Issue by karlbuckland** [libvips/php-vips#86]
I'm using Vips\Image::thumbnail() which is throwing the exception:
vips_colourspace: no known route from 'cmyk' to 'srgb'

Presumably this is because an import ICC profile isn't being specified for CMYK conversions. I have one that I'm using before calling colourspace() later in my code, but in this case the issue is caused by loading the image with thumbnail(). I've tried adding the option 'input_profile', 'iprofile', 'i', etc but none of these are accepted. What is the correct option to pass, or is there another way?

Alternatively, is it reasonably simple for me to use Vips\Image::newFromFile() and then perform the same thumbnail operation separately? I figure I would have to call smartcrop() since I'm using that, and then resize(). Is there anything else clever that thumbnail() does?

**Comment by karlbuckland** [comment]
I see this has been fixed in Vips 8.8.0. I was using 8.7.0 previously.

**Comment by jcupitt** [comment]
Oh, sorry, I thought I'd replied to this but I obviously forgot.
