### ISSUE TITLE
Thread safe

### ISSUE THREAD

**Issue by WyriHaximus** [libvips/php-vips#87]
Been testing this extension out on ZTS PHP in ext-parallel and observed some interesting behavior. Is this extension thread safe and can it be used from within a thread? Or is that unknown/untested at the moment?

**Comment by jcupitt** [comment]
Hello @WyriHaximus, 

libvips itself certainly is, and the extension ought to be as well. I've never experimented with ZTS though so you may well have run into something.

Post a test case if you find an issue and perhaps we can fix it.

**Comment by WyriHaximus** [comment]
Hey @jcupitt 

Will try to put something together later this week. There is a slew of packages involved so I hope the issues is there tbh :smile: .
