### ISSUE TITLE
Scaling unproportionally

### ISSUE THREAD

**Issue by MastroBoy** [libvips/php-vips#89]
Hello @jcupitt,

First of all thank you so much for your library :)

I was trying to migrate an "assets exporter" from ImageMagick to libvips (btw i am using php):
for a resizing algorithm i am working on, i am obliged to scale in a non proportional way an extract_area result image.

my line code is this one:
`$targetWidth = 5;
$targetHeigth = 1661;

$areaResult = $areaResult->resize($targetWidth / $areaResult->width, ['vscale' => $targetHeight / $areaResult->height]);`

Resize operation takes place but result image dimensions are:
before resizing:
width: 6
height: 1760

after resizing:
width: 20
height: 1661

i wish those instead:
width: 5 <------
height: 1661

What am i doing wrong please?

**Comment by jcupitt** [comment]
There have been a few improvements to coordinate rounding in the last couple of years, so I think you probably have rather an old libvips.

I tried your example with current libvips (8.8) and it works:

```
john@kiwi:~/pics$ target_width=5
john@kiwi:~/pics$ target_height=1661
john@kiwi:~/pics$ vips crop wtc.jpg x.jpg 0 0 6 1760
john@kiwi:~/pics$ hscale=$(bc <<< "scale=10; $target_width / 6")
john@kiwi:~/pics$ vscale=$(bc <<< "scale=10; $target_height / 1760")
john@kiwi:~/pics$ vips resize x.jpg x2.jpg $hscale --vscale $vscale
john@kiwi:~/pics$ vipsheader x2.jpg 
x2.jpg: 5x1661 uchar, 3 bands, srgb, jpegload
```

**Comment by MastroBoy** [comment]
Actually yes... i've updated it to 8.8.1 but vip headers are still old (php_info)...
Can you point me towards the right direction on how to update them correclty please?


Vips headers version | 8.2.2  <---- no good
Vips library version | 8.8.1
Vips ABI version | 53.0.11
Major version | 8
Minor version | 8
Micro version | 1

**Comment by jcupitt** [comment]
You need to rebuild `php-vips-ext`, the low-level part of `php-vips`.

Probably just `pecl uninstall vips` then `pecl install vips` to force it to rebuild.

**Comment by MastroBoy** [comment]
Thanks very much!
It solved the problem.
