### ISSUE TITLE
Predominant color with PHP

### ISSUE THREAD

**Issue by jarodium** [libvips/php-vips#92]
Hello

I'm trying to build a placeholder image using the dominant color with the code below.

I was trying to port the python code https://github.com/libvips/libvips/issues/259 but along the way I somehow got lost.
I think I may have messed up somewhere, although the function is clear of errors.
Since I didn't understood this part in the python code ( and thus not being able to convert the code using the docs as a cross-reference ):

```python
//get the pixel at (x, y)
pixel = hist(x, y)

//find the index of the max value in the pixel
band = pixel.index(v)
```

I end up with having B values way above 255 :(

```php
    $N_BINS = 10;
    $BIN_SIZE = 256 / $N_BINS;
    
    $image = Vips\Image::newFromFile("produtos/base2.jpg");
    
    # make a 3D histogram of the RGB image ... 10 bins in each axis
    $hist = $image->hist_find_ndim(["bins" => $N_BINS]);

    $max = $hist->maxpos();
    
    $v = $max[0];
    $x = $max[1];
    $y = $max[2];
    # get the pixel at (x, y)
    $pixel = $image->getpoint($x, $y);
    
    # find the index of the max value in the pixel
    $band = array_keys($pixel, max($pixel));
    # where's $v? maybe getting ready to blow up something? xd
    echo "dominant colour:";
    echo "   R = ". ($x * $BIN_SIZE + $BIN_SIZE / 2);
    echo  "   G = ". ($y * $BIN_SIZE + $BIN_SIZE / 2);
    echo "   B = ". ($pixel[$band[0]] * $BIN_SIZE + $BIN_SIZE / 2);
```

Is there an easier way to get this working?

**Comment by jarodium** [comment]
Hello @jcupitt 
After a week of mind bending for a VIPS only solution I have come up with a less than optimal workaround...

My idea was to "pixelate" the image and then get the dominat colors. Since I don't know much about image processing, I remembered that pixelation will occur if I compress a JPEG with very low quality. So, my idea was to get a 100px wide thumbnail and save it to a buffer. By getting a buffer I can then traverse the pixels and get a color palette ( no doubt some color information will be lost, but I can live with that ) with the N most used colors. Then I just sort the color to find the highest used RGB value and use GD to send an image to the browser... I'm afraid I can't get any faster than 128ms with a 3.5Mb image (3826x2551, 300dpi).

I would prefer creating a VIPS image with $desired_width and $desired_height instead on relying on GD2, but I really don't know how...

Here is my code for the folks in this repo. If this can be improved, please let me know:

```php
require '../vendor/autoload.php';
use Jcupitt\Vips;
Vips\Config::concurrencySet(2);

$mime = "jpeg";
$ext = ".jpg";
$desired_width = 800; //desired width
        
header("Content-type: image/".$mime);
        //open our huge image and thumbnail it to a buffer     
    $image = Vips\Image::newFromFile("produtos/base2.jpg");  
    $image = Vips\Image::thumbnail($f, 100); //thumbnail it to very likely width, since I use 800px wide images in the website
    
        //calculate aspect ratio for guessing the height of final image
    $aspectRatio = $image->height / $image->width;
 
    /* Keep the width fix at $desired_width, but change the height according to the aspect ratio */
    $desired_height = (int)($aspectRatio * $desired_width);
    
        //quality 1 will pixelate as intended
    $buffer = $image->writeToBuffer($ext,["Q" => 1]); 
    
        //load image from buffer
    $image = Vips\Image::newFromBuffer($buffer, '', ['sequential' => true]);
    
        //i could get the average, but I want the dominant color
            //https://stackoverflow.com/questions/3468500/detect-overall-average-color-of-the-picture
    
    $block_size = 20; //variable to traverse blocks
    $colors = [];
    
    for($x=0; $x<$image->width; $x += $block_size) {
        for($y=0; $y<$image->height; $y += $block_size) {
            $rgb = $image->getpoint($x, $y);
            $red = round(round(($rgb[0] / 0x33)) * 0x33); 
            $green = round(round(($rgb[1] / 0x33)) * 0x33); 
            $blue = round(round(($rgb[2] / 0x33)) * 0x33); 
            $hexRGB = sprintf('%02X%02X%02X', $red, $green, $blue); //line is only usefull when dumping for HTML
            $strRGB = $rgb[0].",".$rgb[1].",".$rgb[2];
            if(array_key_exists($strRGB, $colors)) { 
                $colors[$strRGB]++; 
            } 
            else { 
                $colors[$strRGB] = 1; 
            } 
        }
    }
    arsort($colors); //order the array 
    $rgb = array_key_first($colors);
    $rgb = explode(",",$rgb);
    $colors = []; //free mem space?
    
    //create a new image and then fill it with $rgb
        //I find my lack of VIPS knowledge, disturbing
    $im = @imagecreate($desired_width, $desired_height) or die("Cannot Initialize new GD image stream");
    $bg = imagecolorallocate($im, (int)$rgb[0] , (int)$rgb[1], (int)$rgb[2]);
    imagefill($im, 0, 0, $bg);
    imagejpeg($im);
    imagedestroy($im);
    //echo $buffer;
     exit;
´´´

**Comment by jarodium** [comment]
Hello @jcupitt 
I have found this workaround for my specific problem: https://gist.github.com/jarodium/407b70ac41d7fd4c6837565e46474e90

**Comment by jcupitt** [comment]
Hello @jarodium,

Sorry, I started making you some sample code for this last week, then got distracted by something else and forgot to finish it. I was sure I'd posted something.

Anyway, here's a possible solution:

```php
#!/usr/bin/env php
<?php

require __DIR__ . '/vendor/autoload.php';
use Jcupitt\Vips;

$im = Vips\Image::newFromFile($argv[1], ['access' => 'sequential']);

# 3D histogram ... make 10 x 10 x 10 bins, so 1000 possible colours
$n_bins = 10;
$hist = $im->hist_find_ndim(['bins' => $n_bins]);

# black is usually background or boring, so set that cell to 0 counts
# fetch (0, 0, set the 0th element of that to 0, paste back
$pixel = $hist->getpoint(0, 0);
$pixel[0] = 0;
$pixel = Vips\Image::black(1, 1)->add($pixel);
$hist = $hist->insert($pixel, 0, 0);

# check the 3d histogram in nip2 
# $hist->writeToFile("x.v");

# (x, y) pixel with the most counts
[$v, $x, $y] = $hist->maxpos();
$pixel = $hist->getpoint($x, $y);
$z = array_search($v, $pixel);

# convert indexes to rgb ... +0.5 to get the centre of each bin
$r = ($x + 0.5) * 256 / $n_bins;
$g = ($y + 0.5) * 256 / $n_bins;
$b = ($z + 0.5) * 256 / $n_bins;

# make an image with that colour, with the same format / interpretation / 
# size / etc. as the original
$patch = $im->newFromImage([$r, $g, $b]);

$patch->writeToFile($argv[2]);
```

**Comment by jcupitt** [comment]
The only interesting thing it does is set the (0, 0, 0) histogram bin to 0, since black is usually just background.

You mentioned pixelation: is this to make a super low-res image as a placeholder? You'd need something like:

```php
#!/usr/bin/env php
<?php

require __DIR__ . '/vendor/autoload.php';
use Jcupitt\Vips;

# get original size ... this is fast, since pixels will not be decoded until
# they are needed
$original = Vips\Image::newFromFile($argv[1]);

# shrink down to 16 pixels across, keeping the aspect ratio
$thumb = Vips\Image::thumbnail($argv[1], 16);

# expand back up to the size of the original, but using nearest-neighbour 
# so we get large blocks
$placeholder = $thumb->resize($original->width / $thumb->width, [
    'vscale' => $original->height / $thumb->height,
    'kernel' => 'nearest'
]);

$placeholder->writeToFile($argv[2]);
```

**Comment by jarodium** [comment]
Hello @jcupitt 

I was able to merge your pixelation snippet with the code [here](https://gist.github.com/kleisauke/a8cdd74c63738eb3add7d9422458aed8) and got [this](https://gist.github.com/jarodium/407b70ac41d7fd4c6837565e46474e90#file-test2-php) 

It does take a while ( i mean like 800ms ) to read the "inflated" image after the thumbnail and to output the one colored image, but i will be tweaking the vscale values possibly to half or a third to see if I can get more speed. 

As I move to production, I won't be using the > 1mb and 3000px wide images i'm using now, but previously sized images, so i'm aiming to get 40ms image download, greatly improving website's performance.

I just hope intervention image picks up the VIPS backend ASAP xD

Thank you for your help 
Best Regards
jarodium

**Comment by jcupitt** [comment]
Hi again, I think you can make your `test2.php` much simpler. 

Are you trying to make a solid image containing just the dominant colour? You need the test program I made above ^^^, here it is as a gist:

https://gist.github.com/jcupitt/bf233c9efabdb6483dea5c7243777258

Run it like this:

```
$ time ./dominant.php ~/pics/799.jpg x.png
real	0m0.142s
user	0m0.133s
sys	0m0.025s
```

So 140ms for a 1500x625 pixel jpg.

Sample images:

![799](https://user-images.githubusercontent.com/580843/68244981-f1d40400-000d-11ea-925f-11857edf965b.jpg)
![x](https://user-images.githubusercontent.com/580843/68245015-03b5a700-000e-11ea-946c-6c8511884eae.png)

**Comment by jarodium** [comment]
Will take a look.
From the looks of it, that sequential access is kinda scary if by any change my website's users uploads a 3.5mb or bigger image to the website. The CMS's I develop at work already pre-sizes photos ( when intervention adds VIPS, I will have a party at work and my boss will snap at the speed of it xD ) so the users will not be having to download/process images that big.

Will let you know my testing xD

Thank you for the help

**Comment by jarodium** [comment]
Just tested. Damn!!!
These are the results ( all jpegs, output jpeg )

|  SIZE (Mb)  | Wpx x Hpx   |  TIME TO ARRIVE IN BROWSER ( chrome ) |  
|---|---|---|
|  12.55  |   5504x8256  |  6.04s |   
|  0.786   |  6000x3375 |   2.65s |  
|  3.31  |  3826x2551 |   1.38s |  
                                   
                                        
                                       
                                             


Tomorrow I will test it against one of our backoffices to show how fast is this lib.

**Comment by jcupitt** [comment]
That `dominant.php` should work on any size image, though writing a huge solid PNG will take a while. 

If I comment out the `writeToFile` I see:

```
$ /usr/bin/time -f %M:%e ./dominant.php ~/pics/wtc.jpg
57144:0.75
```

ie. 57mb of memory and 750ms of time for a 10k x 10k pixel RGB JPG.

**Comment by jarodium** [comment]
Nice. 
I don't think I will that many large resolutions for the placeholder. Mainly we usually pre-size an image to 1920x1080 tops ( nevermind pixel density ) and we serve that image. But since I have this setup:

http://example.com/WIDTH/path/to/image, I can take advantage of VIPS and quickly prepare X pictures for different devices with the srcset attributes of img's. That 1920x1089 will be delivered beautifully sized ( and fast ) as an image and also a placeholder so that our users ( mainly the pesky metrics software ) won't see any layout elements floating and expanding in the page...
