### ISSUE TITLE
alpine - configure: error: libvips not found

### ISSUE THREAD

**Issue by David-Crty** [libvips/php-vips#93]
When I run ` pecl install vips ` on alpine (3.9) I'm getting the error 

> configure: error: libvips not found.  Check config.log for more information.

But if I check in my container the /usr/lib/libvips.so existe.

Here is the package installed https://pkgs.alpinelinux.org/package/edge/community/x86_64/vips-dev

Everything was working few days ago, I think it's because of an update of vips-dev on alpine.

Is their a way to indicate to pecl the path of libvips ? 

Thanks for everthing.

**Comment by jcupitt** [comment]
pecl is running `configure`, `configure` is using `pkg-config` to locate the libvips headers, and `pkg-config` uses `PKG_CONFIG_PATH`.

So I would try:

```
pkg-config vips --cflags
```

To see if pkg-config can locate your libvips correctly. If it can't, check that you have headers, and check that they are on `PKG_CONFIG_PATH`.

**Comment by David-Crty** [comment]
I have builded the package from source to avoiding the issue.

Thanks again for all the job done, I'm still using every day vips <3
