### ISSUE TITLE
Adding text to an image

### ISSUE THREAD

**Issue by jarodium** [libvips/php-vips#94]
Hello @jcupitt 

I am having some issues using composite, composite2 on adding text to image, from the function below ( copied from @kleisauke 's snippet )

PHP: 7.2.25
Vips: ( version: 8.5.6    ABI: 49.5.7 )

```
function create($width, $height, $color = '#FFFFFF', $format = BandFormat::UCHAR, $interpretation = Interpretation::SRGB): Image
    {
        list($alpha, $red, $green, $blue) = parse($color);
        // Make a 1x1 pixel with the red channel and cast it to provided format.
        $pixel = Image::black(1, 1)->add($red)->cast($format);
        // Extend this 1x1 pixel to match the origin image dimensions.
        $image = $pixel->embed(0, 0, $width, $height, ['extend' => Extend::COPY]);
        // Ensure that the interpretation of the image is set.
        $image = $image->copy(['interpretation' => $interpretation]);
        // Bandwise join the rest of the channels including the alpha channel.
        $image = $image->bandjoin([
            $green,
            $blue,
            $alpha
        ]);

        $text = Vips\Image::text("HELLO", [
            'font' => 'sans 120',
            'width' => $image->width
        ]);

        // Embed text in larger image
        $text = $text->embed(45, 50, $image->width, $image->height);

        $color = [255, 255, 0];
        $reds = $text->newFromImage($color)->copy(['interpretation' => $interpretation]);
        $overlay = $reds->bandjoin($text);
        
        // Set the text alpha
        //$text_alpha = $text->extract_band($text->bands - 1);
        //$text = $text->extract_band(0, ['n' => $text->bands - 1]);

        // Blend the text and the image
        $out = $image->ifthenelse($overlay, $image, ['blend' => true]); //this works but returns black image and yellow text, should return white background

        //$out = $image->composite2($overlay, 'over');
        //$out = $image->composite($overlay, "over", ['x' => 100, 'y' => 100]);
        //    
        return $out;
    }
    $image = create(800, 600 '#FFFFFF');
    $buffer = $image->writeToBuffer($ext);
   echo $buffer;
```
When trying to use composite or composite2 to add the overlay, I get

 thrown in vendor/jcupitt/vips/src/Image.php on line 778
[28-Nov-2019 13:28:22 Europe/Lisbon] PHP Fatal error:  Uncaught Jcupitt\Vips\Exception: VipsOperation: class "composite2" not found
in vendor/jcupitt/vips/src/Image.php:778

I am doing something wrong?

**Comment by jcupitt** [comment]
Hello, `composite` (and `composite2`) were added in 8.6, so I'm afraid you need to update your libvips.

**Comment by jarodium** [comment]
Will do xD.

Thank you

**Comment by jcupitt** [comment]
Here's a simpler way to draw coloured text:

```php
#!/usr/bin/php
<?php
require __DIR__ . '/vendor/autoload.php';
use Jcupitt\Vips;

$image = Vips\Image::newFromFile($argv[1], ['access' => 'sequential']);

// this renders the text to a one-band image ... set width to the pixels across
// of the area we want to render to to have it break lines for you
$text = Vips\Image::text('Hello world!', [
  'font' => 'sans 120',
  'width' => $image->width - 100
]);

// make a constant image the size of $text, but with every pixel red ... tag it
// as srgb
$red = $text->newFromImage([255, 0, 0])->copy(['interpretation' => 'srgb']);

// use the text mask as the alpha for the constant red image
$overlay = $red->bandjoin($text);

// composite the text on the image
$out = $image->composite($overlay, "over", [
  'x' => ($image->width - $overlay->width) / 2,
  'y' => ($image->height - $overlay->height) / 2
]);

$out->writeToFile($argv[2]);
```

Run it like this:

```
$ ./render_text.php ~/pics/Gugg_coloured.jpg x.jpg
```

To make:
![x](https://user-images.githubusercontent.com/580843/69830864-a7196680-121e-11ea-99d1-3f626d74cae7.jpg)

**Comment by jarodium** [comment]
I see. 
I will take another look at it as soon as I update it on the working machine.
The use of composite is a life saver indeed xD.

Thank you for your help
xD

**Comment by jarodium** [comment]
Got it to work. 

Thank you. 

I have the following questions:
1) The only fonts available are "sans" and "bitstream charter" ? I have read these values from the libvips docs.  
2) What is the support for Font Files? Can it load ttf, woff, woff2?
3) The parameter for auto_fit does not make adjustments for font size, right? I mean, at 800px wide i have 120 font-size value. applying auto_fit for 400 will yield 60 font-size. I have to make these calculations myself?

**Comment by jcupitt** [comment]
You can use any font that fontconfig knows about. On this machine, for example:

```
$ fc-list | wc
   1058    4429  105989
```

Just over 1,000 fonts.

Font format support varies with platform and how your freetype2 library has been built. It certainly works for otf, pfb, ttc, ttf. You'd need to experiment.

I'm not sure what you mean by 3). If you specify width and height but don't specify DPI, it'll automatically adjust DPI to try to get the best fit of the text to the box.

```
$ vips text x.png "hello world" --width 800 --height 800
$ vipsheader x.png
x.png: 800x592 uchar, 1 band, b-w, pngload_stream
```

You can read out the DPI it selected with the auto-fit option:

```
$ vips text x.png "hello world" --width 800 --height 800 --autofit-dpi
1830
```

But giving `autofit-dpi` does not enable autofit (if you see what I mean).

**Comment by jarodium** [comment]
The 3) question is more about the equivalent [here](https://stackoverflow.com/questions/289850/auto-font-size-for-text-gd-via-php). This uses imagettfbox for scaling the text. 

Since 'Text' in Vips is an image, I thought about to put in a 100% width relative to the image, and then scale it down, center it, and embed it to the image.

I am now working with the code found in the link above and will let you know how this went xD

**Comment by jcupitt** [comment]
I think `text` does exactly what you want. Just give the width and height of the box you'd like to fill -- you shouldn't need to do any coding. Try that command-line I posted.

Internally, it uses something like ttfbbox (actually the pango equivalent) and adjusts DPI with a binary search.

**Comment by jcupitt** [comment]
```
$ vips text x.png "hello world" --width 300 --height 300
```

Generates:

![x](https://user-images.githubusercontent.com/580843/70239208-cbb39800-1762-11ea-886c-3b08be0bd572.png)

**Comment by jarodium** [comment]
It worked. No matter how I was setting the font size ( 'sans 120', 'sans 20' ) it auto fitted the text to the box.

Thanks :)

**Comment by jcupitt** [comment]
Yes `sans 120` means 120 points (1/72 inch) high, not pixels.

DPI sets how to turn pixels into inches.

**Comment by jcupitt** [comment]
Hi @sergeevabc, just load the file as a string and pass it in.

Could you open new issues for new questions? Otherwise it's hard for other users to find answers.
