### ISSUE TITLE
embed + Extend::WHITE (CMYK image)

### ISSUE THREAD

**Issue by aprat84** [libvips/php-vips#95]
Beginner here!

I want to embed an image and fill the extra space with white color, like so:
```php
$image = $image->embed($x, $y, $w, $h, [
    'extend' => Extend::WHITE,
]);
```

It works well, except when it is a CMYK jpeg. If that's the case, I get black background.

Then, my solution was this, which I don't really know if it is correct:
```php
$image = $image->embed($x, $y, $w, $h, [
    'extend' => Interpretation::CMYK === $image->interpretation 
        ? Extend::BLACK 
        : Extend::WHITE,
]);
```

Is that the expected behavior? Am I doing it right?

I tried to convert colourspace to SRGB, but I get the `no known route between 'cmyk' and 'srgb'` error.

My system:
Ubuntu 18.04.3 LTS
ext-vips 1.0.10
vips-8.4.5

**Comment by jcupitt** [comment]
Hi @aprat84,

Yes, that looks reasonable. In CMYK, 255 means 100% ink, so black.

If you update your libvips to 8.8 it has a built-in cmyk profile, which should fix your `no known route` problem.

**Comment by aprat84** [comment]
> In CMYK, 255 means 100% ink, so black.

I imagined it, but wasn't 100% sure.
We'll try converting to sRGB once v8.8 appears in ubuntu.

Thanks for a fast reply!
Regards.
